enum AgentEvent {
  AGENT_DOWNLOAD_COMPLETE,
  AGENT_FOUND,
  AGENT_START,
  CHANNEL_OPEN_STATUS_CHANGED,
  AGENT_ERROR,
  AGETN_VERSION_UNSUPPORT,
  AGENT_VERSION_SUPPORT,
  DEVICELIST_CHANGED,
  DEVICE_CONNECTED,
  DEVICE_CLOSED
}

enum IDEEvent {
  IMPORT_PROJECT,
  EXPORT_PROJECT,
  EXPORT_COVER,
  NEW_PROJECT,
  CHANGE_MODE,
  CONSOLE_LOG,
  CONSOLE_ERROR,
  CONSOLE_CLEAR,
  SET_TOOLBOX,
  CHANGE_KIT,
  UPLOAD_CODE,
  RESET_TOOLBOX,
  GET_CODE,
  ENABLE_UPLOAD,
  VISIBLE_UPLOAD,
  PAID_USER,
}

export {
  AgentEvent, IDEEvent,
};
