// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.zh.hans');

goog.require('Blockly.Msg');

const LoadArduinoMsgHans = () => {
  Blockly.Msg.ADD_COMMENT = "添加注释";
  Blockly.Msg.ARD_ANALOGREAD = "读取模拟接口#";
  Blockly.Msg.ARD_ANALOGREAD_TIP = "返回0到1024中的一个值";
  Blockly.Msg.ARD_ANALOGWRITE = "设置模拟接口#";
  Blockly.Msg.ARD_ANALOGWRITE_TIP = "将0到255之间的一个模拟值写入到特定的脉宽调制端口";
  Blockly.Msg.ARD_BUILTIN_LED = "设置内置LED灯";
  Blockly.Msg.ARD_BUILTIN_LED_TIP = "设置Arduino版上的内置LED灯状态为开或者关";
  Blockly.Msg.ARD_COMPONENT_WARN1 = "A %1 configuration block with the same %2 name must be added to use this block!"; // untranslated
  Blockly.Msg.ARD_DEFINE = "Define"; // untranslated
  Blockly.Msg.ARD_DIGITALREAD = "读取数字接口#";
  Blockly.Msg.ARD_DIGITALREAD_TIP = "从一端口读取数字值：高电平或低电平";
  Blockly.Msg.ARD_DIGITALWRITE = "设置数字接口#";
  Blockly.Msg.ARD_DIGITALWRITE_TIP = "将数字值高电平或低电平写入特定端口";
  Blockly.Msg.ARD_FUN_RUN_LOOP = "CocoBlockly不断执行:";
  Blockly.Msg.ARD_FUN_RUN_SETUP = "CocoBlockly先执行:";
  Blockly.Msg.ARD_FUN_RUN_TIP = "定义Arduino setup() 和 loop() 函数。";
  Blockly.Msg.ARD_HIGH = "高";
  Blockly.Msg.ARD_HIGHLOW_TIP = "Set a pin state logic High or Low."; // untranslated
  Blockly.Msg.ARD_LOW = "低";
  Blockly.Msg.ARD_MAP = "映射";
  Blockly.Msg.ARD_MAP_TIP = "Re-maps a number from [0-1024] to another."; // untranslated
  Blockly.Msg.ARD_MAP_VAL = "值从[0-";
  Blockly.Msg.ARD_NOTONE_PIN = "No tone"; // untranslated
  Blockly.Msg.ARD_NOTONE_PIN_TIP = "Stop generating a tone on a pin"; // untranslated
  Blockly.Msg.ARD_PIN_WARN1 = "Pin %1 is needed for %2 as pin %3. Already used as %4."; // untranslated
  Blockly.Msg.ARD_NOTONE = "关闭音调 接口#";
  Blockly.Msg.ARD_PULSEON = "脉冲从接口#";
  Blockly.Msg.ARD_PULSEREAD = "读取";
  Blockly.Msg.ARD_PULSETIMEOUT = "超时时间：";
  Blockly.Msg.ARD_PULSETIMEOUT_MS = ""; // untranslated
  Blockly.Msg.ARD_PULSETIMEOUT_TIP = "测量所选接口上脉冲的持续时间，如果其在超时时间内";
  Blockly.Msg.ARD_PULSE_TIP = "测量所选接口上脉冲的持续时间";
  Blockly.Msg.ARD_PWMWRITE = "设置PWM接口#";
  Blockly.Msg.ARD_SERIAL_AVAILABLE = "可用";
  Blockly.Msg.ARD_SERIAL_BPS = "比特/秒";
  Blockly.Msg.ARD_SERIAL_PRINT = "打印";
  Blockly.Msg.ARD_SERIAL_PRINT_NEWLINE = "添加新行";
  Blockly.Msg.ARD_SERIAL_PRINT_TIP = "将数据以可读的ASCII文本形式打印到控制台或串行端口";
  Blockly.Msg.ARD_SERIAL_PRINT_WARN = "Serial相关的初始化积木需要被添加";
  Blockly.Msg.ARD_SERIAL_READ = "读取";
  Blockly.Msg.ARD_SERIAL_SETUP = "设置";
  Blockly.Msg.ARD_SERIAL_SETUP_TIP = "选择特定的串行外设的速度";
  Blockly.Msg.ARD_SERIAL_SPEED = "速度为";
  Blockly.Msg.ARD_SERIAL_WRITE = "写出";
  Blockly.Msg.ARD_SERVO_READ = "读取舵机信息，设置接口为PIN#";
  Blockly.Msg.ARD_SERVO_READ_TIP = "读取舵机的角度";
  Blockly.Msg.ARD_SERVO_SETUP = "舵机初始化";
  Blockly.Msg.ARD_SERVO_WRITE = "定义舵机接口为";
  Blockly.Msg.ARD_SERVO_WRITE_DEG_180 = "度 (0~180)";
  Blockly.Msg.ARD_SERVO_WRITE_TIP = "设置舵机转动一定的角度";
  Blockly.Msg.ARD_SERVO_WRITE_TO = "设置其转动角度为";
  Blockly.Msg.ARD_SPI_SETUP = "设置";
  Blockly.Msg.ARD_SPI_SETUP_CONF = "配置";
  Blockly.Msg.ARD_SPI_SETUP_DIVIDE = "时钟分频";
  Blockly.Msg.ARD_SPI_SETUP_LSBFIRST = "LSBFIRST"; // untranslated
  Blockly.Msg.ARD_SPI_SETUP_MODE = "SPI模式（空 - 边界）";
  Blockly.Msg.ARD_SPI_SETUP_MODE0 = "0 (Low - Falling)"; // untranslated
  Blockly.Msg.ARD_SPI_SETUP_MODE1 = "1 (Low - Rising)"; // untranslated
  Blockly.Msg.ARD_SPI_SETUP_MODE2 = "2 (High - Falling)"; // untranslated
  Blockly.Msg.ARD_SPI_SETUP_MODE3 = "3 (High - Rising)"; // untranslated
  Blockly.Msg.ARD_SPI_SETUP_MSBFIRST = "MSBFIRST"; // untranslated
  Blockly.Msg.ARD_SPI_SETUP_SHIFT = "数据传输";
  Blockly.Msg.ARD_SPI_SETUP_TIP = "配置SPI外设";
  Blockly.Msg.ARD_SPI_TRANSRETURN_TIP = "Send a SPI message to an specified slave device and get data back."; // untranslated
  Blockly.Msg.ARD_SPI_TRANS_NONE = "none"; // untranslated
  Blockly.Msg.ARD_SPI_TRANS_SLAVE = "来控制接口";
  Blockly.Msg.ARD_SPI_TRANS_TIP = "Send a SPI message to an specified slave device."; // untranslated
  Blockly.Msg.ARD_SPI_TRANS_VAL = "转换";
  Blockly.Msg.ARD_SPI_TRANS_WARN1 = "A setup block for %1 must be added to the workspace to use this block!"; // untranslated
  Blockly.Msg.ARD_SPI_TRANS_WARN2 = "Old pin value %1 is no longer available."; // untranslated
  Blockly.Msg.ARD_STEPPER_COMPONENT = "stepper"; // untranslated
  Blockly.Msg.ARD_STEPPER_DEFAULT_NAME = "MyStepper"; // untranslated
  Blockly.Msg.ARD_STEPPER_MOTOR = "步进电机";
  Blockly.Msg.ARD_STEPPER_PIN1 = "接口1#'：";
  Blockly.Msg.ARD_STEPPER_PIN2 = "接口2#'：";
  Blockly.Msg.ARD_STEPPER_REVOLVS = "每转有多少步：";
  Blockly.Msg.ARD_STEPPER_SETUP = "设置步进电机名为：";
  Blockly.Msg.ARD_STEPPER_SETUP_TIP = "配置步进电机接口排列和其他设置";
  Blockly.Msg.ARD_STEPPER_SPEED = "设置转速（转/分）为";
  Blockly.Msg.ARD_STEPPER_STEP = "移动步进电机";
  Blockly.Msg.ARD_STEPPER_STEPS = "步";
  Blockly.Msg.ARD_STEPPER_STEP_TIP = "将步进电机转动一定数量的步数";
  Blockly.Msg.ARD_TIME_CHRONO_CHECK = "当秒表停至";
  Blockly.Msg.ARD_TIME_CHRONO_CHECK1 = "毫秒时";
  Blockly.Msg.ARD_TIME_CHRONO_ELAPSED = "秒表已过去的时间";
  Blockly.Msg.ARD_TIME_CHRONO_RESET = "重置秒表";
  Blockly.Msg.ARD_TIME_CHRONO_SETUP = "秒表初始化";
  Blockly.Msg.ARD_TIME_DELAY = "等待";
  Blockly.Msg.ARD_TIME_DELAY_MICROS = "微秒";
  Blockly.Msg.ARD_TIME_DELAY_MICRO_TIP = "等待一定的时间（以微秒为单位）";
  Blockly.Msg.ARD_TIME_DELAY_TIP = "等待一定的时间（以毫秒为单位）";
  Blockly.Msg.ARD_TIME_DO = "执行";
  Blockly.Msg.ARD_TIME_DO_MS = "执行";
  Blockly.Msg.ARD_TIME_EVERY = "每隔";
  Blockly.Msg.ARD_TIME_EVERY_MS = "每隔";
  Blockly.Msg.ARD_TIME_INF = "永久等待（结束程序）";
  Blockly.Msg.ARD_TIME_INF_TIP = "无限期等待，即停止程序";
  Blockly.Msg.ARD_TIME_MICROS = "当前已过时间（微秒）";
  Blockly.Msg.ARD_TIME_MICROS_TIP = "返回自Arduino版开始执行当前程序以来的微秒数，必须以长整数型储存";
  Blockly.Msg.ARD_TIME_MILLIS = "当前已过时间（毫秒）";
  Blockly.Msg.ARD_TIME_MILLIS_TIP = "返回自Arduino版开始执行当前程序以来的毫秒数，必须以长整数型储存";
  Blockly.Msg.ARD_TIME_MS = "毫秒";
  Blockly.Msg.ARD_TIME_SECOND = "秒";
  Blockly.Msg.ARD_TIME_SECOND_MS = "毫秒";
  Blockly.Msg.ARD_TONE_FREQ = "frequency"; // untranslated
  Blockly.Msg.ARD_TONE_PIN = "Tone PIN#"; // untranslated
  Blockly.Msg.ARD_TONE_PIN_TIP = "Generate audio tones on a pin"; // untranslated
  Blockly.Msg.ARD_TYPE_ARRAY = "Array"; // untranslated
  Blockly.Msg.ARD_TYPE_BOOL = "Boolean"; // untranslated
  Blockly.Msg.ARD_TYPE_CHAR = "Character"; // untranslated
  Blockly.Msg.ARD_TYPE_CHILDBLOCKMISSING = "ChildBlockMissing"; // untranslated
  Blockly.Msg.ARD_TYPE_DECIMAL = "Decimal"; // untranslated
  Blockly.Msg.ARD_TYPE_LONG = "Large Number"; // untranslated
  Blockly.Msg.ARD_TYPE_NULL = "Null"; // untranslated
  Blockly.Msg.ARD_TYPE_NUMBER = "Number"; // untranslated
  Blockly.Msg.ARD_TYPE_SHORT = "Short Number"; // untranslated
  Blockly.Msg.ARD_TYPE_TEXT = "Text"; // untranslated
  Blockly.Msg.ARD_TYPE_UNDEF = "Undefined"; // untranslated
  Blockly.Msg.ARD_VAR_AS = "为";
  Blockly.Msg.ARD_VAR_AS_TIP = "Sets a value to a specific type"; // untranslated
  Blockly.Msg.ARD_WRITE_TO = "为";
  Blockly.Msg.AUTH = "请授权这个应用程序以保存您的作品并共享。";
  Blockly.Msg.BASIC_AS = "as"; // untranslated
  Blockly.Msg.BASIC_BLACK_OUT = "Black out"; // untranslated
  Blockly.Msg.BASIC_BRTN = "Brightness"; // untranslated
  Blockly.Msg.BASIC_BUZZER_PLAY = "Buzzer plays "; // untranslated
  Blockly.Msg.BASIC_BUZZER_SETUP = "Buzzer Setup"; // untranslated
  Blockly.Msg.BASIC_COUNTER_SETTING = "按钮为";
  Blockly.Msg.BASIC_COUNTER_SETUP = "设置一个计数器 ";
  Blockly.Msg.BASIC_FOR = "for"; // untranslated
  Blockly.Msg.BASIC_FROM = "from"; // untranslated
  Blockly.Msg.BASIC_HZ = "Hz"; // untranslated
  Blockly.Msg.BASIC_IF_SWITCH = "If switch "; // untranslated
  Blockly.Msg.BASIC_IS = " is "; // untranslated
  Blockly.Msg.BASIC_LIGHT_PIN = "Light Pin#"; // untranslated
  Blockly.Msg.BASIC_LIGHT_WARNING = "亮度值必须在0到255之间";
  Blockly.Msg.BASIC_MUTE = "Mute"; // untranslated
  Blockly.Msg.BASIC_NOLED = "关闭在接口%1上的灯光";
  Blockly.Msg.BASIC_NOTONE = "关闭在接口%1上的音调";
  Blockly.Msg.BASIC_NOTONE_TIP = "关闭所选接口上的音调输出";
  Blockly.Msg.BASIC_PIN_NUM = "Pin#"; // untranslated
  Blockly.Msg.BASIC_READBUTTON = "读取在接口%1上开关的状态";
  Blockly.Msg.BASIC_READCOUNTER = "读取计数器的数值 计数按钮为%1";
  Blockly.Msg.BASIC_READKNOB = "读取在接口%1上旋钮的数值";
  Blockly.Msg.BASIC_SET = "Set"; // untranslated
  Blockly.Msg.BASIC_SETANALOGLED = "设置在接口%1上的灯光亮度为%2";
  Blockly.Msg.BASIC_SETDIGITALLED = "打开在接口%1上的灯光";
  Blockly.Msg.BASIC_SETTONE = "设置在接口%1上的音调频率为%2";
  Blockly.Msg.BASIC_SET_PIN = "Set Pin#"; // untranslated
  Blockly.Msg.BASIC_TO = "to"; // untranslated
  Blockly.Msg.BASIC_TONE_TIP = "设置接口上的音调频率为31到65535中某个特定频率";
  Blockly.Msg.BASIC_TONE_WARNING = "频率值必须在31到65535之间";
  Blockly.Msg.BLUE = "蓝";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_DATA = "data";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVEMSG = "接收数据";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVEMSG_ISSUCCESS = "接收数据成功";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVE_GET_LINE2 = "获取第";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVE_GET_LINE2_2 = "位的数据";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVE_GET_LINE3 = "位的数据，并设置类型为";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVE_GET_LINE4 = "";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVE_LINE3 = "长度为";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_SENDMSG = "发送数据";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_SETUP = "蓝牙对蓝牙通信";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_SETUP1 = "对蓝牙通信";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_SETUP2 = "初始化";
  Blockly.Msg.BLUETOOTH_LIST_RECEIVED = "已接收到的数组";
  Blockly.Msg.BLUETOOTH_LIST_RECEIVED1 = "中第";
  Blockly.Msg.BLUETOOTH_LIST_RECEIVED2 = "位的值";
  Blockly.Msg.BLUETOOTH_NUMBER_RECEIVED = "已接收到的数字";
  Blockly.Msg.BLUETOOTH_PAIRING_BIND_ADDR = "绑定从属装置地址:";
  Blockly.Msg.BLUETOOTH_PAIRING_MASTER = "蓝牙配对: 设置为主机装置";
  Blockly.Msg.BLUETOOTH_PAIRING_SETTING_BAUDRATE = "设置波特率:";
  Blockly.Msg.BLUETOOTH_PAIRING_SETTING_TIMEOUT = "设置延时:";
  Blockly.Msg.BLUETOOTH_PAIRING_SLAVE = "蓝牙配对: 设置为从属装置";
  Blockly.Msg.BLUETOOTH_SETUP = "当蓝牙接收到";
  Blockly.Msg.BLUETOOTH_SETUP_DO = "并且做";
  Blockly.Msg.BLUETOOTH_SETUP_LIST_SETTING = "长度为";
  Blockly.Msg.BLUETOOTH_SETUP_OPT1 = "一串文字";
  Blockly.Msg.BLUETOOTH_SETUP_OPT2 = "一个数字";
  Blockly.Msg.BLUETOOTH_SETUP_OPT3 = "一个数组";
  Blockly.Msg.BLUETOOTH_SETUP_SET = "设置";
  Blockly.Msg.BLUETOOTH_SETUP_TO = "为接收到的信息";
  Blockly.Msg.BLUETOOTH_TEXT_RECEIVED = "已接收到的字符串";
  Blockly.Msg.BLYNK_AUTH = "认证密匙: ";
  Blockly.Msg.BLYNK_CONNECT = "当Blynk连接成功";
  Blockly.Msg.BLYNK_CREATE_WITH_CONTAINER_TITLE_ADD = "Data";
  Blockly.Msg.BLYNK_CREATE_WITH_ITEM_TITLE = "item";
  Blockly.Msg.BLYNK_DATA = "data";
  Blockly.Msg.BLYNK_GET_DATANAME = "从";
  Blockly.Msg.BLYNK_GET_DATANAME1 = "获得";
  Blockly.Msg.BLYNK_GET_DATANAME2 = "数据";
  Blockly.Msg.BLYNK_GET_INDEX = "第";
  Blockly.Msg.BLYNK_GET_INDEX1 = "位的数据";
  Blockly.Msg.BLYNK_GET_OF = "获得数据";
  Blockly.Msg.BLYNK_GET_OF1 = "获得";
  Blockly.Msg.BLYNK_GET_OF2 = "的数据";
  Blockly.Msg.BLYNK_GPS_ALTITUDE = "高度(海拔)";
  Blockly.Msg.BLYNK_GPS_LATITUDE = "纬度";
  Blockly.Msg.BLYNK_GPS_LONGITUDE = "经度";
  Blockly.Msg.BLYNK_GPS_SPEED = "速度";
  Blockly.Msg.BLYNK_LOG = "BLYNK_LOG";
  Blockly.Msg.BLYNK_PW = "WiFi密码: ";
  Blockly.Msg.BLYNK_READ = "当Blynk请求";
  Blockly.Msg.BLYNK_READ1 = "数据";
  Blockly.Msg.BLYNK_SELECT = "选择";
  Blockly.Msg.BLYNK_SETUP = "BLYNK初始化";
  Blockly.Msg.BLYNK_SSID = "WiFi名称: ";
  Blockly.Msg.BLYNK_TIME_DO = "执行";
  Blockly.Msg.BLYNK_TIME_SECOND = "秒";
  Blockly.Msg.BLYNK_TIME_SETTING = "设置计时器: 每隔";
  Blockly.Msg.BLYNK_VIRTUALWRITE = "發送數據到";
  Blockly.Msg.BLYNK_VIRTUALWRITE_DATA = "Data:";
  Blockly.Msg.BLYNK_WIFI = "连接WiFi网络";
  Blockly.Msg.BLYNK_WRITE = "从";
  Blockly.Msg.BLYNK_WRITE1 = "获取数据";
  Blockly.Msg.BLYNK_WRITE_VARIABLE = "存到";
  Blockly.Msg.BLYNK_WRITE_VARLENGTH = "长度";
  Blockly.Msg.CHANGE_VALUE_TITLE = "更改值：";
  Blockly.Msg.CHAT = "通过在此框输入与您的合作者沟通！";
  Blockly.Msg.CLEAN_UP = "整理块";
  Blockly.Msg.CLOUDDATA_CREATE_WITH_CONTAINER_TITLE_ADD = "key[]";
  Blockly.Msg.CLOUDDATA_CREATE_WITH_INPUT_WITH = "添加";
  Blockly.Msg.CLOUDDATA_CREATE_WITH_ITEM_TITLE = "value";
  Blockly.Msg.CLOUDDATA_GENERATOR_DATA = "生成数据";
  Blockly.Msg.CLOUDDATA_PARSE_JSON = "的数据从";
  Blockly.Msg.CLOUDDATA_PARSE_KEY = "解析得到名为";
  Blockly.Msg.CLOUDDATA_PARSE_PRETTYPRINT_DISPLAY = "获得生成的数据";
  Blockly.Msg.CLOUDDATA_PARSE_SETUP_INIT = "数据解析初始化为";
  Blockly.Msg.CLOUDDATA_PARSE_SETUP_PAYLOAD = "解析内容";
  Blockly.Msg.CLOUDDATA_PARSE_TYPE = "类型为";
  Blockly.Msg.COCOCLOUD_CREATE_WITH_CONTAINER_TITLE_ADD = "LIST";
  Blockly.Msg.COCOCLOUD_CREATE_WITH_ITEM_TITLE = "Event";
  Blockly.Msg.COCOCLOUD_GET = "向项目";
  Blockly.Msg.COCOCLOUD_GET1 = " 获取数据";
  Blockly.Msg.COCOCLOUD_GETPAYLOAD = "从项目获取到的数据";
  Blockly.Msg.COCOCLOUD_POST = "发送到项目";
  Blockly.Msg.COCOCLOUD_POST_DATA = "数据";
  Blockly.Msg.COCOCLOUD_TIME_DAY = "日";
  Blockly.Msg.COCOCLOUD_TIME_GETDATE = "获取";
  Blockly.Msg.COCOCLOUD_TIME_GETTIME = "获取";
  Blockly.Msg.COCOCLOUD_TIME_HOUR = "时";
  Blockly.Msg.COCOCLOUD_TIME_MINUTE = "分";
  Blockly.Msg.COCOCLOUD_TIME_MONTH = "月份";
  Blockly.Msg.COCOCLOUD_TIME_SECOND = "秒";
  Blockly.Msg.COCOCLOUD_TIME_SETUP = "世界时间";
  Blockly.Msg.COCOCLOUD_TIME_YEAR = "年份";
  Blockly.Msg.COCOCLOUD_TITLE = "Web服务 CocoCloud";
  Blockly.Msg.COLLAPSE_ALL = "折叠块";
  Blockly.Msg.COLLAPSE_BLOCK = "折叠块";
  Blockly.Msg.COLOR = "颜色";
  Blockly.Msg.COLORANALYZER_SETUP = "颜色分析设置";
  Blockly.Msg.COLOUR_BLEND_COLOUR1 = "颜色1";
  Blockly.Msg.COLOUR_BLEND_COLOUR2 = "颜色2";
  Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/"; // untranslated
  Blockly.Msg.COLOUR_BLEND_RATIO = "比例";
  Blockly.Msg.COLOUR_BLEND_TITLE = "混合";
  Blockly.Msg.COLOUR_BLEND_TOOLTIP = "用一个给定的比率(0.0-1.0)混合两种颜色。";
  Blockly.Msg.COLOUR_PICKER_HELPURL = "https://zh.wikipedia.org/wiki/颜色";
  Blockly.Msg.COLOUR_PICKER_TOOLTIP = "从调色板中选择一种颜色。";
  Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com"; // untranslated
  Blockly.Msg.COLOUR_RANDOM_TITLE = "随机颜色";
  Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "随机选择一种颜色。";
  Blockly.Msg.COLOUR_RGB_BLUE = "蓝色";
  Blockly.Msg.COLOUR_RGB_GREEN = "绿色";
  Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html"; // untranslated
  Blockly.Msg.COLOUR_RGB_RED = "红色";
  Blockly.Msg.COLOUR_RGB_TITLE = "颜色";
  Blockly.Msg.COLOUR_RGB_TOOLTIP = "通过指定红色、绿色和蓝色的量创建一种颜色。所有的值必须介于0和100之间。";
  Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks"; // untranslated
  Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "中断循环";
  Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "继续下一次循环";
  Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "中断包含它的循环。";
  Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "跳过这个循环的剩余部分，并继续下一次迭代。";
  Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "警告：此块仅可用于在一个循环内。";
  Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each"; // untranslated
  Blockly.Msg.CONTROLS_FOREACH_TITLE = "为每个项目 %1 在列表中 %2";
  Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "遍历每个列表中的项目，将变量“%1”设定到该项中，然后执行某些语句。";
  Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with"; // untranslated
  Blockly.Msg.CONTROLS_FOR_TITLE = "使用 %1 从范围 %2 到 %3 每隔 %4";
  Blockly.Msg.CONTROLS_FOR_TOOLTIP = "从起始数到结尾数中取出变量“%1”的值，按指定的时间间隔，执行指定的块。";
  Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "在if语句块中增加一个条件。";
  Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "添加一个最终的，包括所有情况的节到if块中。";
  Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse"; // untranslated
  Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "增加、删除或重新排列各节来重新配置“if”块。";
  Blockly.Msg.CONTROLS_IF_MSG_ELSE = "否则";
  Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "否则如果";
  Blockly.Msg.CONTROLS_IF_MSG_IF = "如果";
  Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "如果值为真，执行一些语句。";
  Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "如果值为真，则执行语句的第一块。否则，则执行语句的第二块。";
  Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "如果第一个值为真，则执行语句的第一个块。否则，如果第二个值为真，则执行语句的第二块。";
  Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "如果第一个值为真，则执行语句的第一块。否则，如果第二个值为真，则执行语句的第二块。如果没有值为真，则执行语句的最后一块。";
  Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://zh.wikipedia.org/wiki/For循环";
  Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "执行";
  Blockly.Msg.CONTROLS_REPEAT_TITLE = "重复 %1 次";
  Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "多次执行一些语句。";
  Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat"; // untranslated
  Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "重复直到";
  Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "重复当";
  Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "只要值为假，执行一些语句。";
  Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "只要值为真，执行一些语句。";
  Blockly.Msg.DELETE_ALL_BLOCKS = "删除所有%1块吗？";
  Blockly.Msg.DELETE_BLOCK = "删除块";
  Blockly.Msg.DELETE_X_BLOCKS = "删除 %1 块";
  Blockly.Msg.DISABLE_BLOCK = "禁用块";
  Blockly.Msg.DUPLICATE_BLOCK = "复制";
  Blockly.Msg.ENABLE_BLOCK = "启用块";
  Blockly.Msg.ENCODER_GETROTATIONSPEED = "读取码盘数值";
  Blockly.Msg.ENCODER_SETUP = "码盘初始化";
  Blockly.Msg.ENCODER_SETUP_1 = "设定中断引脚";
  Blockly.Msg.ENV_AS = "as"; // untranslated
  Blockly.Msg.ENV_BLUE_PIN = "蓝 从接口";
  Blockly.Msg.ENV_BUZZER_ALARM = "Buzzer Alarm"; // untranslated
  Blockly.Msg.ENV_CRITICAL_VAL = "When the critical value of"; // untranslated
  Blockly.Msg.ENV_DO = "Do"; // untranslated
  Blockly.Msg.ENV_GREEN_PIN = "绿 从接口";
  Blockly.Msg.ENV_REACHES = "reaches"; // untranslated
  Blockly.Msg.ENV_RED_PIN = "红 从接口";
  Blockly.Msg.ENV_SENSOR_HUMID = "读取湿度的数值从接口 ";
  Blockly.Msg.ENV_SENSOR_HUMIDITY = "湿度";
  Blockly.Msg.ENV_SENSOR_LIGHT = " 读取光照的数值从接口 ";
  Blockly.Msg.ENV_SENSOR_MIC = " 读取声音的数值从接口 ";
  Blockly.Msg.ENV_SENSOR_READ = "读取数值从";
  Blockly.Msg.ENV_SENSOR_READTEMP = "读取温度的数值从接口 ";
  Blockly.Msg.ENV_SENSOR_SET_RGB = "设置RGB灯光";
  Blockly.Msg.ENV_SENSOR_SOUND = "声音";
  Blockly.Msg.ENV_SENSOR_TEMPUNIT = "设置单位为";
  Blockly.Msg.ENV_SENSOR_UNITC = "摄氏度";
  Blockly.Msg.ENV_SENSOR_UNITF = "华氏度";
  Blockly.Msg.ENV_SET = "Set"; // untranslated
  Blockly.Msg.ENV_SETRGB_B = "蓝 从接口";
  Blockly.Msg.ENV_SETRGB_G = "绿 从接口";
  Blockly.Msg.ENV_SETRGB_R = "红 从接口 ";
  Blockly.Msg.ENV_SETUP = "环境感应设置";
  Blockly.Msg.ENV_SET_TEMP = "Set temperature as "; // untranslated
  Blockly.Msg.ENV_SET_TEMP_UNIT = "Set unit as "; // untranslated
  Blockly.Msg.EXPAND_ALL = "展开块";
  Blockly.Msg.EXPAND_BLOCK = "展开块";
  Blockly.Msg.EXPORTPNG = "导出PNG快照";
  Blockly.Msg.EXPORTXML = "导出XML文件";
  Blockly.Msg.EXTERNAL_INPUTS = "外部输入";
  Blockly.Msg.Friday = "周五";
  Blockly.Msg.GPS_LATITUDE = "获取纬度";
  Blockly.Msg.GPS_LONGITUDE = "获取经度";
  Blockly.Msg.GPS_SETUP = "GPS 初始化";
  Blockly.Msg.GREEN = "绿";
  Blockly.Msg.HELP = "帮助";
  Blockly.Msg.HID_KEYBOARD_PRESS = "设置键盘: 按下";
  Blockly.Msg.HID_KEYBOARD_RELEASE = "设置键盘: 释放";
  Blockly.Msg.HID_KEYBOARD_RELEASEALL = "设置键盘: 释放全部";
  Blockly.Msg.HID_MOUSE_CLICK = "设置鼠标: 点击";
  Blockly.Msg.HID_MOUSE_CLICK_LEFT = "左键";
  Blockly.Msg.HID_MOUSE_CLICK_RIGHT = "右键";
  Blockly.Msg.HID_MOUSE_MOVE = "设置鼠标: 向";
  Blockly.Msg.HID_MOUSE_MOVE_DISTANCE = "px";
  Blockly.Msg.HID_MOUSE_MOVE_FOR = "移动";
  Blockly.Msg.HID_MOUSE_PRESS = "设置鼠标: 按下";
  Blockly.Msg.HID_MOUSE_RELEASE = "设置鼠标: 松开";
  Blockly.Msg.HID_SETUP = "HID初始化";
  Blockly.Msg.INFRAREDRAY_RECVAL = "接收值";
  Blockly.Msg.INFRAREDRAY_SETUP = "红外线接收器设置";
  Blockly.Msg.INLINE_INPUTS = "单行输入";
  Blockly.Msg.ISCOLOR = "是否颜色";
  Blockly.Msg.JSONOBJECT_CREATE = "JSON Object"; // untranslated
  Blockly.Msg.JSONTOOL_ARRAY_SIZE = "数组大小";
  Blockly.Msg.JSONTOOL_GENERATOR = "JSON构造器 ";
  Blockly.Msg.JSONTOOL_GENERATOR_ARRAY_VALUE = "JSON数组加入: value";
  Blockly.Msg.JSONTOOL_GENERATOR_JSONOBJECT = "Object";
  Blockly.Msg.JSONTOOL_GENERATOR_KEY = "JSON对象加入：Key ";
  Blockly.Msg.JSONTOOL_GENERATOR_MAIN_JSONNAME = "JSONVar";
  Blockly.Msg.JSONTOOL_GENERATOR_MAIN_TITLE = "生成JSON";
  Blockly.Msg.JSONTOOL_GENERATOR_MAIN_TITLE_NAME = "命名为";
  Blockly.Msg.JSONTOOL_GENERATOR_NESTED_TITLE = "嵌套JSON";
  Blockly.Msg.JSONTOOL_GENERATOR_NESTED_TITLE_NAME = "命名为";
  Blockly.Msg.JSONTOOL_GENERATOR_SETUP = "JSON构造器初始化";
  Blockly.Msg.JSONTOOL_GENERATOR_VALUE = "Value";
  Blockly.Msg.JSONTOOL_OBJECT_SIZE = "对象大小";
  Blockly.Msg.JSONTOOL_PARSE_ARRAY = "(JSON数组)";
  Blockly.Msg.JSONTOOL_PARSE_BY = "获取";
  Blockly.Msg.JSONTOOL_PARSE_EACH = "从JSON对象";
  Blockly.Msg.JSONTOOL_PARSE_INDEX = "下标为";
  Blockly.Msg.JSONTOOL_PARSE_ISSUCCESS = "是否成功解析";
  Blockly.Msg.JSONTOOL_PARSE_ISSUCCESS_NAME = "对于JSON对象";
  Blockly.Msg.JSONTOOL_PARSE_JSONOBJECT = "Object";
  Blockly.Msg.JSONTOOL_PARSE_KEY = "(JSON对象)key";
  Blockly.Msg.JSONTOOL_PARSE_KEYVALUE = "从JSON Object %1 获得key %2 的值";
  Blockly.Msg.JSONTOOL_PARSE_NEST = "内嵌";
  Blockly.Msg.JSONTOOL_PARSE_PRETTYPRINT = "打印 JSON ";
  Blockly.Msg.JSONTOOL_PARSE_PRETTYPRINT_DISPLAY = "规范化数据";
  Blockly.Msg.JSONTOOL_PARSE_PRETTYPRINT_WAY = "按规范方式";
  Blockly.Msg.JSONTOOL_PARSE_RESPONSE = "数据内容";
  Blockly.Msg.JSONTOOL_PARSE_SETUP = "JSON解析器初始化";
  Blockly.Msg.JSONTOOL_PARSE_TOVAR = "获取数据到";
  Blockly.Msg.JSONTOOL_PARSE_VARTYPE = "";
  Blockly.Msg.LED_BACKCOLOR = "背景";
  Blockly.Msg.LED_BRIGHTNESS_WARNING = "亮度应该在范围 0 - 255 之间";
  Blockly.Msg.LED_BRTN = "亮度";
  Blockly.Msg.LED_CLEAR = "清除";
  Blockly.Msg.LED_COLOR = "颜色";
  Blockly.Msg.LED_COORDINATE = "坐标";
  Blockly.Msg.LED_DRAW = "画";
  Blockly.Msg.LED_FONT = "字体";
  Blockly.Msg.LED_FULL = "实心";
  Blockly.Msg.LED_HEIGHT = "高";
  Blockly.Msg.LED_LINE = "线";
  Blockly.Msg.LED_LINE_END = "终点";
  Blockly.Msg.LED_LINE_START = "起点";
  Blockly.Msg.LED_MULTICOM = "H"; // untranslated
  Blockly.Msg.LED_PANELHEIGHT = "高(拼接个数)";
  Blockly.Msg.LED_PANELWIDTH = "宽(拼接个数)";
  Blockly.Msg.LED_PATTERN = "图形";
  Blockly.Msg.LED_PIN = "接口";
  Blockly.Msg.LED_PIXEL = "点";
  Blockly.Msg.LED_POSITION = "位置";
  Blockly.Msg.LED_RECTANGLE = "矩形";
  Blockly.Msg.LED_SCROLL = "滚动";
  Blockly.Msg.LED_SCROLL_NO = "否";
  Blockly.Msg.LED_SCROLL_SPEED = "速度";
  Blockly.Msg.LED_SCROLL_YES = "是";
  Blockly.Msg.LED_SETUP = "LED灯组设置";
  Blockly.Msg.LED_SET_BRIGHTNESS = "设置亮度为";
  Blockly.Msg.LED_SET_ROTATION = "将屏幕旋转至";
  Blockly.Msg.LED_SET_ROTATION_DEGREE = "度";
  Blockly.Msg.LED_SHOW_ALL = "显示图案";
  Blockly.Msg.LED_SINGLE_SETUP = "单个LED灯组设置";
  Blockly.Msg.LED_SIZE = "大小";
  Blockly.Msg.LED_STRIP_LOCATION = "位置";
  Blockly.Msg.LED_STRIP_PIXEL = "绘制像素";
  Blockly.Msg.LED_STROKED = "空心";
  Blockly.Msg.LED_TEXT = "文本";
  Blockly.Msg.LED_WIDTH = "宽";
  Blockly.Msg.LED_WORD = "单字";
  Blockly.Msg.LIGHT_BRIGHTNESS = "上的灯光亮度为：";
  Blockly.Msg.LIGHT_PIN = "设置";
  Blockly.Msg.LIGHT_TURNOFF = "关闭灯光输出在";
  Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";
  Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "创建空列表";
  Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "返回一个列表，长度为 0，不包含任何数据记录";
  Blockly.Msg.LISTS_CREATE_LIST_WITH = "创建数组";
  Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "列表";
  Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "增加、删除或重新排列各部分以此重新配置这个列表块。";
  Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
  Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "将一个项添加到列表中。";
  Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "建立一个具有任意数量项目的列表。";
  Blockly.Msg.LISTS_GETINDEX = "从数组 %1 中获取第 %2 位的值";
  Blockly.Msg.LISTS_GET_INDEX_FIRST = "第一";
  Blockly.Msg.LISTS_GET_INDEX_FROM_END = "倒数第#";
  Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
  Blockly.Msg.LISTS_GET_INDEX_GET = "获得";
  Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "取出并移除";
  Blockly.Msg.LISTS_GET_INDEX_LAST = "最后";
  Blockly.Msg.LISTS_GET_INDEX_RANDOM = "随机";
  Blockly.Msg.LISTS_GET_INDEX_REMOVE = "移除";
  Blockly.Msg.LISTS_GET_INDEX_TAIL = "空白";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "返回列表中的第一个项目。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "返回在列表中的指定位置的项。#1是最后一项。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "返回在列表中的指定位置的项。#1是第一个项目。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "返回列表中的最后一项。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "随机返回列表中的一个项目。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "移除并返回列表中的第一个项目。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "移除并返回列表中的指定位置的项。#1 是最后一项。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "移除并返回列表中的指定位置的项。#1 是第一项。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "移除并返回列表中的最后一个项目。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "移除并返回列表中的一个随机项目中。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "移除列表中的第一项";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "删除在列表中的指定位置的项。#1是最后一项。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "移除在列表中的指定位置的项。#1 是第一项。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "移除列表中的最后一项";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "删除列表中的一个随机的项。";
  Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "到倒数第#";
  Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "到#";
  Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "到最后";
  Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist"; // untranslated
  Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "从头获得子列表";
  Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "从倒数#取得子列表";
  Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "从#取得子列表";
  Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "空白";
  Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "复制列表中指定的部分。";
  Blockly.Msg.LISTS_INDEX_OF_FIRST = "找出第一个项出现";
  Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list"; // untranslated
  Blockly.Msg.LISTS_INDEX_OF_LAST = "找出最后一个项出现";
  Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "返回在列表中的第一/最后一个匹配项的索引值。如果找不到项目则返回0。";
  Blockly.Msg.LISTS_INLIST = "在列表中";
  Blockly.Msg.LISTS_INT_CREATE_WITH_INPUT_WITH = "建立数字数组使用";
  Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty"; // untranslated
  Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1是空的";
  Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "如果改列表为空，则返回真。";
  Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of"; // untranslated
  Blockly.Msg.LISTS_LENGTH_TITLE = "%1的长度";
  Blockly.Msg.LISTS_LENGTH_TOOLTIP = "返回列表的长度。";
  Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with"; // untranslated
  Blockly.Msg.LISTS_REPEAT_TITLE = "建立列表使用项 %1 重复 %2 次";
  Blockly.Msg.LISTS_REPEAT_TOOLTIP = "建立包含指定重复次数的值的列表。";
  Blockly.Msg.LISTS_SETINDEX = "赋值 %1 中第 %2 位的值到 %3";
  Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set"; // untranslated
  Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "为";
  Blockly.Msg.LISTS_SET_INDEX_INSERT = "插入在";
  Blockly.Msg.LISTS_SET_INDEX_SET = "设置";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "在列表的起始处添加该项。";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "插入在列表中的指定位置的项。#1是最后一项。";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "插入在列表中指定位置的项。#1是第一项。";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "将该项追加到列表的末尾。";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "在列表中随机插入项。";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "设置列表中的第一个项目。";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "设置在列表中指定位置的项。#1是最后一项。";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "设置在列表中指定位置的项。#1是第一项。";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "设置列表中的最后一项。";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "设置列表中一个随机的项目。";
  Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
  Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "升序";
  Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "降序";
  Blockly.Msg.LISTS_SORT_TITLE = "排序%1 %2 %3";
  Blockly.Msg.LISTS_SORT_TOOLTIP = "排序一个列表的拷贝。";
  Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "按字母排序，忽略大小写";
  Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "按数字排序";
  Blockly.Msg.LISTS_SORT_TYPE_TEXT = "按字母排序";
  Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
  Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "从文本制作列表";
  Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "从列表拆出文本";
  Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "加入文本列表至一个文本，由分隔符分隔。";
  Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "拆分文本到文本列表，按每个分隔符拆分。";
  Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "用分隔符";
  Blockly.Msg.LISTS_STRING_CREATE_WITH_INPUT_WITH = "建立字符串数组使用";
  Blockly.Msg.LISTS_THE_LENGTH_OF = "%1的长度";
  Blockly.Msg.LOGIC_BOOLEAN_FALSE = "假";
  Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values"; // untranslated
  Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "返回真或假。";
  Blockly.Msg.LOGIC_BOOLEAN_TRUE = "真";
  Blockly.Msg.LOGIC_CASE = "情况";
  Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://zh.wikipedia.org/wiki/不等";
  Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "如果两个输入结果相等，则返回真。";
  Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "如果第一个输入结果比第二个大，则返回真。";
  Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "如果第一个输入结果大于或等于第二个输入结果，则返回真。";
  Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "如果第一个输入结果比第二个小，则返回真。";
  Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "如果第一个输入结果小于或等于第二个输入结果，则返回真。";
  Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "如果两个输入结果不相等，则返回真。";
  Blockly.Msg.LOGIC_DEFAULT = "默认";
  Blockly.Msg.LOGIC_DO = "做";
  Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";
  Blockly.Msg.LOGIC_NEGATE_TITLE = "非%1";
  Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "如果输入结果为假，则返回真；如果输入结果为真，则返回假。";
  Blockly.Msg.LOGIC_NULL = "空";
  Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type"; // untranslated
  Blockly.Msg.LOGIC_NULL_TOOLTIP = "返回空值。";
  Blockly.Msg.LOGIC_OPERATION_AND = "和";
  Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations"; // untranslated
  Blockly.Msg.LOGIC_OPERATION_OR = "或";
  Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "如果两个输入结果都为真，则返回真。";
  Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "如果至少有一个输入结果为真，则返回真。";
  Blockly.Msg.LOGIC_SWITCH = "切换";
  Blockly.Msg.LOGIC_TERNARY_CONDITION = "测试";
  Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://zh.wikipedia.org/wiki/条件运算符";
  Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "如果为假";
  Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "如果为真";
  Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "检查“test”中的条件。如果条件为真，则返回“if true”的值，否则，则返回“if false”的值。";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE = "从WiFi模塊获取数据";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE_GET = "从";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE_GET_LINE2 = "获取第";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE_GET_LINE3 = "位的数据，并设置类型为";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE_GET_LINE4 = "";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE_LINE2 = "并存到 ";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE_LINE3 = "长度为 ";
  Blockly.Msg.MAINEASYMODE_TRANSFER_SEND = "创建数组";
  Blockly.Msg.MAINEASYMODE_TRANSFER_SEND_LINE2 = "发送数据到WiFi上";
  Blockly.Msg.MAINEASYMODE_TRANSFER_SEND_VALUE = "Data";
  Blockly.Msg.MAINWIFI_RECEIVEMSG = "接收数据到 ";
  Blockly.Msg.MAINWIFI_RECEIVEMSG_ISSUCCESS = "接收数据成功";
  Blockly.Msg.MAINWIFI_RECEIVEMSG_LENGTH = ",数据长度为 ";
  Blockly.Msg.MAINWIFI_SENDMSG = "发送数据";
  Blockly.Msg.MAINWIFI_SENDMSG_LENGTH = ",数据长度为";
  Blockly.Msg.MAINWIFI_SETUP = "无线数据传输初始化";
  Blockly.Msg.MATH_ADDITION_SYMBOL = "+"; // untranslated
  Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://zh.wikipedia.org/wiki/算术";
  Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "返回两个数字的和。";
  Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "返回两个数字的商。";
  Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "返回两个数字的区别。";
  Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "返回两个数字的乘积。";
  Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "返回第一个数的第二个数次幂。";
  Blockly.Msg.MATH_CHANGE_HELPURL = "https://zh.wikipedia.org/wiki/%E5%8A%A0%E6%B3%95";
  Blockly.Msg.MATH_CHANGE_TITLE = "更改 %1 由 %2";
  Blockly.Msg.MATH_CHANGE_TOOLTIP = "将一个数添加到变量“%1”。";
  Blockly.Msg.MATH_CONSTANT_HELPURL = "https://zh.wikipedia.org/wiki/数学常数";
  Blockly.Msg.MATH_CONSTANT_TOOLTIP = "返回一个常见常量：π (3.141......)，e (2.718...)、φ (1.618...)、 sqrt(2) (1.414......)、sqrt(½) (0.707......)或 ∞（无穷大）。";
  Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29"; // untranslated
  Blockly.Msg.MATH_CONSTRAIN_TITLE = "限制数字 %1 介于 (低) %2 到 (高) %3";
  Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "限制数字介于两个指定的数字之间";
  Blockly.Msg.MATH_DIVISION_SYMBOL = "÷"; // untranslated
  Blockly.Msg.MATH_IS_DIVISIBLE_BY = "可被整除";
  Blockly.Msg.MATH_IS_EVEN = "是偶数";
  Blockly.Msg.MATH_IS_NEGATIVE = "为负";
  Blockly.Msg.MATH_IS_ODD = "是奇数";
  Blockly.Msg.MATH_IS_POSITIVE = "为正";
  Blockly.Msg.MATH_IS_PRIME = "是质数";
  Blockly.Msg.MATH_IS_TOOLTIP = "如果数字是偶数、奇数、非负整数、正数、负数或如果它可被某数字整除，则返回真或假。";
  Blockly.Msg.MATH_IS_WHOLE = "为整数";
  Blockly.Msg.MATH_MODULO_HELPURL = "https://zh.wikipedia.org/wiki/模除";
  Blockly.Msg.MATH_MODULO_TITLE = "取余数自 %1 ÷ %2";
  Blockly.Msg.MATH_MODULO_TOOLTIP = "返回这两个数字相除后的余数。";
  Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×"; // untranslated
  Blockly.Msg.MATH_NUMBER_HELPURL = "https://zh.wikipedia.org/wiki/数";
  Blockly.Msg.MATH_NUMBER_TOOLTIP = "一个数字。";
  Blockly.Msg.MATH_ONLIST_HELPURL = ""; // untranslated
  Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "列表中的平均数";
  Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "列表中的最大值";
  Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "列表中位数";
  Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "列表中的最小值";
  Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "列表模式";
  Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "列表的随机项";
  Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "列表中的标准差";
  Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "列表中的数的总和";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "返回列表中的数值的平均值。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "返回列表中最大数。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "返回列表中的中位数。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "返回列表中最小数。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "返回列表中的最常见的项的列表。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "从列表中返回一个随机的元素。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "返回列表的标准偏差。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "返回列表中的所有数字的和。";
  Blockly.Msg.MATH_POWER_SYMBOL = "^"; // untranslated
  Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://zh.wikipedia.org/wiki/随机数生成器";
  Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "随机分数";
  Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "返回介于（包含）0.0到1.0之间的随机数。";
  Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://zh.wikipedia.org/wiki/随机数生成器";
  Blockly.Msg.MATH_RANDOM_INT_TITLE = "从 %1 到 %2 之间的随机整数";
  Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "返回两个指定的范围（含）之间的随机整数。";
  Blockly.Msg.MATH_ROUND_HELPURL = "https://zh.wikipedia.org/wiki/数值修约";
  Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "四舍五入";
  Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "向下舍入";
  Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "向上舍入";
  Blockly.Msg.MATH_ROUND_TOOLTIP = "数字向上或向下舍入。";
  Blockly.Msg.MATH_SINGLE_HELPURL = "https://zh.wikipedia.org/wiki/平方根";
  Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "绝对";
  Blockly.Msg.MATH_SINGLE_OP_ROOT = "平方根";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "返回一个数的绝对值。";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "返回数的e次幂。";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "返回一个数的自然对数。";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "返回数字的对数。";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "返回数的逻辑非。";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "返回数的10次幂。";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "返回数的平方根。";
  Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-"; // untranslated
  Blockly.Msg.MATH_TRIG_ACOS = "acos"; // untranslated
  Blockly.Msg.MATH_TRIG_ASIN = "asin"; // untranslated
  Blockly.Msg.MATH_TRIG_ATAN = "atan"; // untranslated
  Blockly.Msg.MATH_TRIG_COS = "cos"; // untranslated
  Blockly.Msg.MATH_TRIG_HELPURL = "https://zh.wikipedia.org/wiki/三角函数";
  Blockly.Msg.MATH_TRIG_SIN = "sin"; // untranslated
  Blockly.Msg.MATH_TRIG_TAN = "tan"; // untranslated
  Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "返回一个数的反余弦值。";
  Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "返回一个数的反正弦值。";
  Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "返回指定角度的反正切值。";
  Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "返回指定角度的余弦值(非弧度）。";
  Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "返回指定角度的正弦值(非弧度）。";
  Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "返回指定角度的正切值(非弧度）。";
  Blockly.Msg.MATH_MAX_MIN_OPERATOR_MAX = "最大值";
  Blockly.Msg.MATH_MAX_MIN_OPERATOR_MIN = "最小值";
  Blockly.Msg.MATH_MAX_MIN_TOOLTIP = "返回两个数字的最大值/最小值";
  Blockly.Msg.MATH_MAX_MIN_HELPURL = "https://www.arduino.cc/reference/en/language/functions/math/max/";
  Blockly.Msg.ME = "我";
  Blockly.Msg.MOTION_GETACC = "获取";
  Blockly.Msg.MOTION_GETACC1 = "方向的加速度";
  Blockly.Msg.MOTION_GETRAWDATA = "获得数据";
  Blockly.Msg.MOTION_GETYPR = "获取";
  Blockly.Msg.MOTION_GETYPR1 = "的旋转度";
  Blockly.Msg.MOTION_ONDIRECTION = "正在向";
  Blockly.Msg.MOTION_ONDIRECTION1 = "偏转";
  Blockly.Msg.MOTION_ONDIRECTION_BACK = "后";
  Blockly.Msg.MOTION_ONDIRECTION_CLOCKWISE = "顺时针";
  Blockly.Msg.MOTION_ONDIRECTION_COUNTERCLOCKWISE = "逆时针";
  Blockly.Msg.MOTION_ONDIRECTION_FRONT = "前";
  Blockly.Msg.MOTION_ONDIRECTION_LEFT = "左";
  Blockly.Msg.MOTION_ONDIRECTION_RIGHT = "右";
  Blockly.Msg.MOTION_ONSHAKE = "正在摇晃";
  Blockly.Msg.MOTION_SETUP = "运动初始化";
  Blockly.Msg.MOTION_TRENDENCY = "获得运动趋势";
  Blockly.Msg.MOTOR_MOVE_DIRECTION1 = "顺时针";
  Blockly.Msg.MOTOR_MOVE_DIRECTION2 = "逆时针";
  Blockly.Msg.MOTOR_MOVE_MOTOR = "驱动电机";
  Blockly.Msg.MOTOR_MOVE_MSG = "和";
  Blockly.Msg.MOTOR_SETUP = "电机驱动车设置";
  Blockly.Msg.MOTOR_SPEED = "速度";
  Blockly.Msg.MOTOR_STOP = "设置电机停止";
  Blockly.Msg.MUSIC_BEAT = "拍";
  Blockly.Msg.MUSIC_DURATION = "持续";
  Blockly.Msg.MUSIC_INSTRUMENT = "设定乐器";
  Blockly.Msg.MUSIC_INSTRUMENT_ACCORION = "手风琴";
  Blockly.Msg.MUSIC_INSTRUMENT_BASS = "贝斯";
  Blockly.Msg.MUSIC_INSTRUMENT_CELLO = "大提琴";
  Blockly.Msg.MUSIC_INSTRUMENT_DRAWBARORGAN = "爵士风琴";
  Blockly.Msg.MUSIC_INSTRUMENT_DRUM = "鼓";
  Blockly.Msg.MUSIC_INSTRUMENT_EGUITAR = "电吉他";
  Blockly.Msg.MUSIC_INSTRUMENT_EPIANO = "电子琴";
  Blockly.Msg.MUSIC_INSTRUMENT_FLUTE = "长笛";
  Blockly.Msg.MUSIC_INSTRUMENT_GPIANO = "经典钢琴";
  Blockly.Msg.MUSIC_INSTRUMENT_GUITAR = "吉他";
  Blockly.Msg.MUSIC_INSTRUMENT_MUSICBOX = "八音盒";
  Blockly.Msg.MUSIC_INSTRUMENT_PICCOLO = "短笛";
  Blockly.Msg.MUSIC_INSTRUMENT_SAX = "萨克斯";
  Blockly.Msg.MUSIC_INSTRUMENT_SITAR = "西塔琴";
  Blockly.Msg.MUSIC_INSTRUMENT_TRUMPET = "喇叭";
  Blockly.Msg.MUSIC_INSTRUMENT_VIOLA = "中提琴";
  Blockly.Msg.MUSIC_INSTRUMENT_VIOLIN = "小提琴";
  Blockly.Msg.MUSIC_INSTRUMENT_WHISTLE = "汽笛";
  Blockly.Msg.MUSIC_INSTRUMENT_WOODBLOCK = "木鱼";
  Blockly.Msg.MUSIC_INSTRUMENT_XYLOPHONE = "木琴";
  Blockly.Msg.MUSIC_MP3_CURRENTVOLUME = "获得当前音量";
  Blockly.Msg.MUSIC_MP3_PLAYALL = "播放列表";
  Blockly.Msg.MUSIC_MP3_PLAYALL_NAME = "播放模式";
  Blockly.Msg.MUSIC_MP3_PLAYMODE_LISTREPEAT = "列表循环";
  Blockly.Msg.MUSIC_MP3_PLAYMODE_NORMAL = "单次";
  Blockly.Msg.MUSIC_MP3_PLAYMODE_REPEAT = "单曲循环";
  Blockly.Msg.MUSIC_MP3_PLAYONE = "播放音乐文件";
  Blockly.Msg.MUSIC_MP3_PLAYONE_NAME = "音乐:";
  Blockly.Msg.MUSIC_MP3_PLAYONE_NORMAL = "单次";
  Blockly.Msg.MUSIC_MP3_PLAYONE_REPEAT = "循环";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING = "播放器设置:";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_NEXTSONG = "下一曲";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_PAUSE = "暂停";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_PLAYALL = "播放所有乐曲";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_PRESONG = "上一曲";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_RESUME = "播放";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_STOP = "停止";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_VOLDOWN = "调小音量";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_VOLUP = "调大音量";
  Blockly.Msg.MUSIC_MP3_PLAY_NORMAL = "顺序播放";
  Blockly.Msg.MUSIC_MP3_PLAY_REPEAT = "列表循环";
  Blockly.Msg.MUSIC_MP3_SETUP = "MP3播放器初始化";
  Blockly.Msg.MUSIC_MP3_SETUP_SETVOLUME = "设置音量";
  Blockly.Msg.MUSIC_MP3_SETUP_SETVOLUME_HIGH = "高";
  Blockly.Msg.MUSIC_MP3_SETUP_SETVOLUME_LOW = "低";
  Blockly.Msg.MUSIC_MP3_SETUP_SETVOLUME_MID = "中";
  Blockly.Msg.MUSIC_MP3_SETVOLUME = "设置音量为";
  Blockly.Msg.MUSIC_NOTE = "音阶";
  Blockly.Msg.MUSIC_PLAY_NOTE = "播放";
  Blockly.Msg.MUSIC_PLAY_NOTE_TOOLTIP = "right click this block and check the help page to see the corresponding music note."; // untranslated
  Blockly.Msg.MUSIC_REST = "音符间隔";
  Blockly.Msg.MUSIC_VOLUME = "设置音量";
  Blockly.Msg.MUSIC_VOL_MAX = "最大";
  Blockly.Msg.MUSIC_VOL_MIN = "最小";
  Blockly.Msg.Monday = "周一";
  Blockly.Msg.Motion_Accelerate = "加速度";
  Blockly.Msg.Motion_Gyroscope = "陀螺仪";
  Blockly.Msg.NBIOT_ENABLE = "启用NB-IoT 串口命令交互";
  Blockly.Msg.NBIOT_HTTP_APIKEY = "云端事件API密匙";
  Blockly.Msg.NBIOT_HTTP_CLOUD_GET = "NB-IoT CocoCloud: Receive Data"; // untranslated
  Blockly.Msg.NBIOT_HTTP_CONTENTTYPE = "Content Type"; // untranslated
  Blockly.Msg.NBIOT_HTTP_DATA = "数据名称";
  Blockly.Msg.NBIOT_HTTP_IFTTT_APIKEY = "IFTTT API Key";
  Blockly.Msg.NBIOT_HTTP_IFTTT_EVENT = "IFTTT项目名称";
  Blockly.Msg.NBIOT_HTTP_IFTTT_TITLE = "NB-IoT 连接IFTTT:发送数据";
  Blockly.Msg.NBIOT_HTTP_THINGSPEAK_APIKEY = "事件API密匙";
  Blockly.Msg.NBIOT_HTTP_THINGSPEAK_TITLE = "NB-IoT 连接Thingspeak:发送数据";
  Blockly.Msg.NBIOT_HTTP_TITLE = "NB-IoT 连接CocoCloud:发送数据";
  Blockly.Msg.NBIOT_IS_POWERON = "NB-IoT 模块启动成功";
  Blockly.Msg.NBIOT_NETWORK_CONNECTED = "网络连接成功";
  Blockly.Msg.NBIOT_NETWORK_IP = "获取  NB-IoT 模块 IP 地址";
  Blockly.Msg.NBIOT_SETUP = "NB-IoT 通信初始化";
  Blockly.Msg.NEW_INSTANCE = "New instance..."; // untranslated
  Blockly.Msg.NEW_INSTANCE_TITLE = "New instance name:"; // untranslated
  Blockly.Msg.NEW_VARIABLE = "新变量...";
  Blockly.Msg.NEW_VARIABLE_TITLE = "新变量的名称：";
  Blockly.Msg.OLED_CENTER_POS = "圆心坐标";
  Blockly.Msg.OLED_CIRCLE = "圆形";
  Blockly.Msg.OLED_CLEAR = "清除";
  Blockly.Msg.OLED_COLOR = "颜色";
  Blockly.Msg.OLED_COORDINATE = "起始点坐标";
  Blockly.Msg.OLED_DRAW = "画";
  Blockly.Msg.OLED_FALSE = "否";
  Blockly.Msg.OLED_FULL = "实心";
  Blockly.Msg.OLED_HEIGHT = "高";
  Blockly.Msg.OLED_LINE = "线";
  Blockly.Msg.OLED_LINE_END = "到";
  Blockly.Msg.OLED_LINE_START = "从";
  Blockly.Msg.OLED_POINT = "点";
  Blockly.Msg.OLED_POSITION = "位置";
  Blockly.Msg.OLED_RADIUS = "设置半径为";
  Blockly.Msg.OLED_RECTANGLE = "矩形";
  Blockly.Msg.OLED_SETROTATION = "将屏幕旋转";
  Blockly.Msg.OLED_SETROTATION_DEGREE = "度";
  Blockly.Msg.OLED_SETUP = "OLED屏幕设置";
  Blockly.Msg.OLED_SIZE = "尺寸";
  Blockly.Msg.OLED_STROKED = "空心";
  Blockly.Msg.OLED_TEXT = "文本";
  Blockly.Msg.OLED_TEXTNEWLINE = "换行";
  Blockly.Msg.OLED_TRIANGLE = "三角形";
  Blockly.Msg.OLED_TRUE = "是";
  Blockly.Msg.OLED_WIDTH = "宽";
  Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "空白";
  Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "允许声明";
  Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "与：";
  Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程序";
  Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "运行用户定义的函数“%1”。";
  Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程序";
  Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "运行用户定义的函数“%1”，并使用它的输出值。";
  Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "与：";
  Blockly.Msg.PROCEDURES_CREATE_DO = "创建“%1”";
  Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "描述该功能...";
  Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "空白";
  Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程序";
  Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "func1";
  Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "至";
  Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "创建一个不带输出值的函数。";
  Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程序";
  Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "返回";
  Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "创建一个有输出值的函数。";
  Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "警告: 此函数具有重复参数。";
  Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "突出显示函数定义";
  Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";
  Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "如果值为真，则返回第二个值。";
  Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "警告: 仅在定义函数内可使用此块。";
  Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "输入名称：";
  Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "添加函数输入。";
  Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "输入";
  Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "添加、删除或重新排此函数的输入。";
  Blockly.Msg.PULSESENSOR_GETBPM = "读取心率值";
  Blockly.Msg.PULSESENSOR_HEARTBEAT_PRINT = "在串口监视器中打印心率原始数据";
  Blockly.Msg.PULSESENSOR_HEARTBEAT_WHEN = "当心率跳动时";
  Blockly.Msg.PULSESENSOR_HEARTBEAT_WHENNO = "当心率未跳动时";
  Blockly.Msg.PULSESENSOR_SETUP = "心率传感器设置";
  Blockly.Msg.PULSESENSOR_SETUP_1 = "设置传感器的接口为";
  Blockly.Msg.READ_B = "读取蓝";
  Blockly.Msg.READ_G = "读取绿";
  Blockly.Msg.READ_R = "读取红";
  Blockly.Msg.RED = "红";
  Blockly.Msg.REDO = "重做";
  Blockly.Msg.REMOVE_COMMENT = "删除注释";
  Blockly.Msg.RENAME_INSTANCE = "Rename instance..."; // untranslated
  Blockly.Msg.RENAME_INSTANCE_TITLE = "Rename all '%1' instances to:"; // untranslated
  Blockly.Msg.RENAME_VARIABLE = "重命名变量...";
  Blockly.Msg.RENAME_VARIABLE_TITLE = "将所有“%1”变量重命名为:";
  Blockly.Msg.REQUEST_DATA_CLOUD = "云端数据";
  Blockly.Msg.REQUEST_DATA_STRING = "字符串";
  Blockly.Msg.RFID_READID = "读取卡片ID";
  Blockly.Msg.RFID_SETUP = "RFID初始化";
  Blockly.Msg.ROBOT_SETMOVE_MOVEMENT = "设置双足的动作";
  Blockly.Msg.ROBOT_SETMOVE_TEMPO = "在速度为";
  Blockly.Msg.ROBOT_SETUP = "双足行走机器人设置";
  Blockly.Msg.ROBOT_SETUP_SETRLPIN = "和左脚接口";
  Blockly.Msg.ROBOT_SETUP_SETRRPIN = "设置右脚接口";
  Blockly.Msg.ROBOT_SETUP_SETYLPIN = "和左膝接口";
  Blockly.Msg.ROBOT_SETUP_SETYRPIN = "设置右膝接口";
  Blockly.Msg.RTC_DAY = "日";
  Blockly.Msg.RTC_GETDATE = "获取当前日期";
  Blockly.Msg.RTC_GETTIME = "获取当前时间";
  Blockly.Msg.RTC_GETWEEK = "获取当前周数";
  Blockly.Msg.RTC_HOUR = "时";
  Blockly.Msg.RTC_MINUTE = "分";
  Blockly.Msg.RTC_MONTH = "月";
  Blockly.Msg.RTC_SECOND = "秒";
  Blockly.Msg.RTC_SETDATE = "日期";
  Blockly.Msg.RTC_SETDATETIME = "设置日期时间";
  Blockly.Msg.RTC_SETTIME = "时钟";
  Blockly.Msg.RTC_SETUP = "RTC初始化";
  Blockly.Msg.RTC_SETWEEK = "周数";
  Blockly.Msg.RTC_WEEK = "周";
  Blockly.Msg.RTC_YEAR = "年";
  Blockly.Msg.SONAR = "超声波";
  Blockly.Msg.SONAR_READ_DIST = "读取距离从";
  Blockly.Msg.SONAR_SETUP = "设置";
  Blockly.Msg.SONAR_SETUP_ECHOPIN = "和 Echo";
  Blockly.Msg.SONAR_SETUP_MAXDIST = "设置最大距离";
  Blockly.Msg.SONAR_SETUP_TRIGPIN = "设置 Trig";
  Blockly.Msg.Saturday = "周六";
  Blockly.Msg.Sunday = "周日";
  Blockly.Msg.TEXT_APPEND_APPENDTEXT = "追加文本";
  Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification"; // untranslated
  Blockly.Msg.TEXT_APPEND_TO = "在";
  Blockly.Msg.TEXT_APPEND_TOOLTIP = "将一些文本追加到变量“%1”。";
  Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case"; // untranslated
  Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "为小写";
  Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "为首字母大写";
  Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "为大写";
  Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "使用不同的大小写复制这段文字。";
  Blockly.Msg.TEXT_CHARAT_FIRST = "获得第一个字符";
  Blockly.Msg.TEXT_CHARAT_FROM_END = "获得倒数第#个字符";
  Blockly.Msg.TEXT_CHARAT_FROM_START = "获得字符#";
  Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text"; // untranslated
  Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "于文本中";
  Blockly.Msg.TEXT_CHARAT_LAST = "获得最后一个字符";
  Blockly.Msg.TEXT_CHARAT_RANDOM = "获取随机的字母";
  Blockly.Msg.TEXT_CHARAT_TAIL = "空白";
  Blockly.Msg.TEXT_CHARAT_TOOLTIP = "返回位于指定位置的字母。";
  Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "将一个项添加到文本中。";
  Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "加入";
  Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "添加、移除或重新排列各节来重新配置这个文本块。";
  Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "到倒数第#个字符";
  Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "到字符#";
  Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "到最后一个字符";
  Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text"; // untranslated
  Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "自文本";
  Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "取得一段字串自第一个字符";
  Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "取得一段字串自#到末尾";
  Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "取得一段字串自#";
  Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "空白";
  Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "返回指定的部分文本。";
  Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text"; // untranslated
  Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "自文本";
  Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "寻找第一个出现的文本";
  Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "寻找最后一个出现的文本";
  Blockly.Msg.TEXT_INDEXOF_TAIL = "空白";
  Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "返回在第二个字串中的第一/最后一个匹配项的索引值。如果未找到则返回 0。";
  Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text"; // untranslated
  Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1是空的";
  Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "如果提供的文本为空，则返回真。";
  Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation"; // untranslated
  Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "建立字串使用";
  Blockly.Msg.TEXT_JOIN_TOOLTIP = "通过串起任意数量的项以建立一段文字。";
  Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification"; // untranslated
  Blockly.Msg.TEXT_LENGTH_TITLE = "%1的长度";
  Blockly.Msg.TEXT_LENGTH_TOOLTIP = "返回提供文本的字母数（包括空格）。";
  Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text"; // untranslated
  Blockly.Msg.TEXT_PRINT_TITLE = "打印%1";
  Blockly.Msg.TEXT_PRINT_TOOLTIP = "打印指定的文字、数字或其他值。";
  Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user"; // untranslated
  Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "提示用户输入数字。";
  Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "提示用户输入一些文本。";
  Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "输入数字并显示提示消息";
  Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "输入数字并显示提示消息";
  Blockly.Msg.TEXT_TEXT_HELPURL = "https://zh.wikipedia.org/wiki/字符串";
  Blockly.Msg.TEXT_TEXT_TOOLTIP = "一个字母、单词或一行文本。";
  Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces"; // untranslated
  Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "消除两侧空格";
  Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "消除左侧空格";
  Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "消除右侧空格";
  Blockly.Msg.TEXT_TRIM_TOOLTIP = "复制这段文字的同时删除两端多余的空格。";
  Blockly.Msg.THINGSPEAK_CREATE_WITH_CONTAINER_TITLE_ADD = "Field";
  Blockly.Msg.THINGSPEAK_CREATE_WITH_INPUT_WITH = "FIELD";
  Blockly.Msg.THINGSPEAK_CREATE_WITH_ITEM_TITLE = "value";
  Blockly.Msg.TODAY = "今天";
  Blockly.Msg.TOUCH_AT = "触摸传感接口 ";
  Blockly.Msg.TOUCH_CASE = "按键";
  Blockly.Msg.TOUCH_DEFAULT = "默认";
  Blockly.Msg.TOUCH_DO = "执行";
  Blockly.Msg.TOUCH_LOOSE = "当松开时";
  Blockly.Msg.TOUCH_SETUP = "触摸感应设置";
  Blockly.Msg.TOUCH_SWITCH = "⌘ 当触碰传感接口";
  Blockly.Msg.TOUCH_THEN_LOOSE_SWITCH = "⌘ 当松开被触碰的接口";
  Blockly.Msg.Thursday = "周四";
  Blockly.Msg.Tuesday = "周二";
  Blockly.Msg.UNDO = "撤销";
  Blockly.Msg.VARIABLES_DEFAULT_NAME = "item"; // untranslated
  Blockly.Msg.VARIABLES_GET_CREATE_SET = "创建“设定%1”";
  Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get"; // untranslated
  Blockly.Msg.VARIABLES_GET_TOOLTIP = "返回此变量的值。";
  Blockly.Msg.VARIABLES_SET = "赋值 %1 为 %2";
  Blockly.Msg.VARIABLES_SET_CREATE_GET = "创建“获得%1”";
  Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set"; // untranslated
  Blockly.Msg.VARIABLES_SET_TOOLTIP = "设置此变量，以使它和输入值相等。";
  Blockly.Msg.WATERTEMP_GET_TEMP = "获取水温数值 (ºC)";
  Blockly.Msg.WATERTEMP_SETUP_ATTACHED_PIN = "数字引脚设定:";
  Blockly.Msg.WATERTEMP_SETUP_BLOCKNAME = "水温传感器";
  Blockly.Msg.WATERTEMP_SETUP_SENSORTYPE = "传感器型号:";
  Blockly.Msg.WATERTEMP_SETUP_SETUP = "初始化";
  Blockly.Msg.WEBPAGE_BUTTONCTRL_SETPATH = " set path to:"; // untranslated
  Blockly.Msg.WEBPAGE_BUTTONCTRL_TEXT_BOTTOM = "设置底部按钮为:";
  Blockly.Msg.WEBPAGE_BUTTONCTRL_TEXT_CENTER = "设置中间按钮为:";
  Blockly.Msg.WEBPAGE_BUTTONCTRL_TEXT_LEFT = "设置左侧按钮为:";
  Blockly.Msg.WEBPAGE_BUTTONCTRL_TEXT_RIGHT = "设置右侧按钮为:";
  Blockly.Msg.WEBPAGE_BUTTONCTRL_TEXT_TOP = "设置顶部按钮为:";
  Blockly.Msg.WEBPAGE_BUTTONCTRL_TITLE = "网页控制面板: 按键控制器";
  Blockly.Msg.WEBPAGE_BUTTON_NAME = "按钮名称";
  Blockly.Msg.WEBPAGE_BUTTON_ROUTER = "设置请求路径为:";
  Blockly.Msg.WEBPAGE_BUTTON_TITLE = "网页控制面板: 按钮";
  Blockly.Msg.WEBPAGE_COLORPICKER_PATH = "设置请求路径为:";
  Blockly.Msg.WEBPAGE_COLORPICKER_SUBTITLE = "*注意: 传输的颜色数据为 RGB 颜色制式";
  Blockly.Msg.WEBPAGE_COLORPICKER_TITLE = "网页控制面板: 取色器控件";
  Blockly.Msg.WEBPAGE_LABLE = "标签名称";
  Blockly.Msg.WEBPAGE_LABLE_TITLE = "网页控制面板: 文本";
  Blockly.Msg.WIFICLIENT_HTTP_GET_DATA = "获取数据并存到";
  Blockly.Msg.WIFICLIENT_HTTP_GET_URL = "发送GET请求到";
  Blockly.Msg.WIFICLIENT_HTTP_POST_DATA = "数据";
  Blockly.Msg.WIFICLIENT_HTTP_POST_TYPE = "类型为";
  Blockly.Msg.WIFICLIENT_HTTP_POST_URL = "发送POST请求到";
  Blockly.Msg.WIFICLIENT_HTTP_POST_VAR = "创建数组";
  Blockly.Msg.WIFICLIENT_HTTP_PUT_DATA = "要发送内容";
  Blockly.Msg.WIFICLIENT_HTTP_PUT_TYPE = "类型为";
  Blockly.Msg.WIFICLIENT_HTTP_PUT_URL = "发送PUT请求到";
  Blockly.Msg.WIFICLIENT_HTTP_RESPONSE = "获得HTTP响应";
  Blockly.Msg.WIFICLIENT_HTTP_SETUP = "客戶端初始化";
  Blockly.Msg.WIFICLIENT_RECEIVE_GET = "从";
  Blockly.Msg.WIFICLIENT_RECEIVE_GET_LINE2 = "获取第";
  Blockly.Msg.WIFICLIENT_RECEIVE_GET_LINE3 = "位的数据,类型为";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_END = "值";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_GETDATA = "获取数据并将其存到";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_KEY = "从";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_KEY1 = "获取云端项目中";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_KEY2 = "属性名为";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_SENDDATA = "发送数据:";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_SETVAR = "变量";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_SETVAR_FROM = "";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_TYPE = "的";
  Blockly.Msg.WIFIEASYMODE_COCOClOUD_DATA_NAME = "数据名:";
  Blockly.Msg.WIFIEASYMODE_COCOClOUD_EVENT = "Cloud Event API Key :";
  Blockly.Msg.WIFIEASYMODE_IFTTT_EVENT = "IFTTT项目名称:";
  Blockly.Msg.WIFIEASYMODE_IFTTT_FETCH = "获取数据";
  Blockly.Msg.WIFIEASYMODE_IFTTT_KEY = "IFTTT Key:";
  Blockly.Msg.WIFIEASYMODE_IFTTT_POST = "发送数据";
  Blockly.Msg.WIFIEASYMODE_IFTTT_SENDDATA = "发送数据:";
  Blockly.Msg.WIFIEASYMODE_IFTTT_TYPE = "Webhook类型:";
  Blockly.Msg.WIFIEASYMODE_NETWORK_PW = "密码:";
  Blockly.Msg.WIFIEASYMODE_NETWORK_SSID = "SSID:";
  Blockly.Msg.WIFIEASYMODE_NETWORK_TITLE = "连接Wi-Fi";
  Blockly.Msg.WIFIEASYMODE_THINGSPEAK_APIKEY = "Channel API Key:";
  Blockly.Msg.WIFIEASYMODE_THINGSPEAK_SENDDATA = "发送数据:";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE = "从主控获取数据";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE_GET = "从";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE_GET_LINE2 = "获取第";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE_GET_LINE3 = "位的数据，并设置类型为";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE_GET_LINE4 = "";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE_LINE2 = "并存到";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE_LINE3 = "长度为 ";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_SEND = "创建数组";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_SEND_LINE2 = "发送数据到主控上";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_SEND_VALUE = "Data";
  Blockly.Msg.WIFINETWORK_AP_PW = "密码:";
  Blockly.Msg.WIFINETWORK_AP_SETUP = "建立Wi-Fi热点";
  Blockly.Msg.WIFINETWORK_AP_SSID = "SSID:";
  Blockly.Msg.WIFINETWORK_CONNECT = "连接Wi-Fi";
  Blockly.Msg.WIFINETWORK_CONNECT_PW = "密码:";
  Blockly.Msg.WIFINETWORK_CONNECT_SSID = "SSID:";
  Blockly.Msg.WIFINETWORK_GETGATEWAYIP = "获取网关IP";
  Blockly.Msg.WIFINETWORK_GETLOCALIP = "获取本地IP";
  Blockly.Msg.WIFINETWORK_GETMACADDR = "获取MAC地址";
  Blockly.Msg.WIFINETWORK_GETSTATIONNUM = "获取连接设备数量";
  Blockly.Msg.WIFINETWORK_ISCONNECTED = "是否成功连接";
  Blockly.Msg.WIFINETWORK_PW_WARN = "密码设置应该超过8位";
  Blockly.Msg.WIFISERVER_HANDLECLIENT = "handleclient";
  Blockly.Msg.WIFISERVER_LIST = "创建数组";
  Blockly.Msg.WIFISERVER_RECEIVE = "服务器接收数据";
  Blockly.Msg.WIFISERVER_RECEIVE_GET = "从";
  Blockly.Msg.WIFISERVER_RECEIVE_GET_INT = "数字";
  Blockly.Msg.WIFISERVER_RECEIVE_GET_LINE2 = "获取第";
  Blockly.Msg.WIFISERVER_RECEIVE_GET_LINE3 = "位的值,类型为";
  Blockly.Msg.WIFISERVER_RECEIVE_GET_STRING = "字符串";
  Blockly.Msg.WIFISERVER_RECEIVE_LENGTH = "长度为";
  Blockly.Msg.WIFISERVER_RECEIVE_TO = "并存储到";
  Blockly.Msg.WIFISERVER_SEND = "服务器发送数据";
  Blockly.Msg.WIFISERVER_SERVERSEND = "服务器 推送 ";
  Blockly.Msg.WIFISERVER_SERVERSEND_CODE = "HTTP 状态码";
  Blockly.Msg.WIFISERVER_SERVERSEND_CONTENT = "内容";
  Blockly.Msg.WIFISERVER_SERVERSEND_TYPE = "类型";
  Blockly.Msg.WIFISERVER_SETROOTPAGE = "设置主页";
  Blockly.Msg.WIFISERVER_SETROUTER = "服务器路由";
  Blockly.Msg.WIFISERVER_SETROUTER_ONNOTFOUND = "设置服务器路由当不存在URL时, 处理";
  Blockly.Msg.WIFISERVER_SETROUTER_SET = "设置路径";
  Blockly.Msg.WIFISERVER_SETROUTER_WITH = "响应";
  Blockly.Msg.WIFISERVER_SETUP = "服务器初始化";
  Blockly.Msg.WIFISERVER_WAIT_CONNECTION = "等待连接";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT = "Web服务 IFTTT";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_EVENT = "Event";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_KEY = "Api-Key ";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_KEY1 = "Key1";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_KEY2 = "Key2";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_KEY3 = "Key3";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_VALUE1 = "Value1";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_VALUE2 = "Value2";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_VALUE3 = "Value3";
  Blockly.Msg.WIFIWEBSERVICES_THINKSPEAK = "Web服务 Thinkspeak";
  Blockly.Msg.WIFIWEBSERVICES_THINKSPEAK_SET_FIELD1 = "Field";
  Blockly.Msg.WIFIWEBSERVICES_THINKSPEAK_SET_KEY = "Api-key";
  Blockly.Msg.WIFIWEBSERVICES_THINKSPEAK_SET_VALUE = "Value";
  Blockly.Msg.WIFI_RECEIVEMSG = "接收数据至";
  Blockly.Msg.WIFI_RECEIVEMSG_ISSUCCESS = "接收数据成功";
  Blockly.Msg.WIFI_RECEIVEMSG_LENGTH = ", 数据长度 ";
  Blockly.Msg.WIFI_SENDMSG = "发送数据 ";
  Blockly.Msg.WIFI_SENDMSG_LENGTH = ", 数据长度 ";
  Blockly.Msg.WIFI_SETUP = "数据传输初始化";
  Blockly.Msg.Wednesday = "周三";
  Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
  Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
  Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
  Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
  Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
  Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
  Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
  Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
  Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
  Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
  Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
  Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
  Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
  Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
  Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
  Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
  Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
  Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
  Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
  Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;

  Blockly.Msg.MATH_RANDOM_SEED = "生成随机数种子 %1";

  Blockly.Msg.EVENT_WHENDEVICEOPEN_INITIALIZE = "初始化";
  Blockly.Msg.EVENT_WHENDEVICEOPEN_REPEATDO = "重复";
  Blockly.Msg.MDCONTROL_TIME_SECOND = "秒";
  Blockly.Msg.MDCONTROL_REPEAT_ONE = "重复";
  Blockly.Msg.MDCONTROL_IF_THEN = "那么";
  Blockly.Msg.MDCONTROL_ELSE = "否则";
  Blockly.Msg.MIC_CLOSED = "关";
  Blockly.Msg.MIC_LED_LITE_COLOR = "LED彩灯亮";
  Blockly.Msg.MIC_MATRIX = "显示";
  Blockly.Msg.MIC_LED_SHOW_TEXT = "显示文本";
  Blockly.Msg.MIC_LED_NOTES = "蜂鸣器";
  Blockly.Msg.MIC_LED_NOTES_TONES = "音调";
  Blockly.Msg.MIC_LITE_PRESS = "按下";
  Blockly.Msg.MIC_LITE_BUTTON = "按扭?";
  Blockly.Msg.MIC_LITE_TOUCH = "触摸";
  Blockly.Msg.MIC_LITE_CLEAR_SCREEN = "清空屏幕";
  Blockly.Msg.MIC_LITE_A_TASKET = "丢手绢";
  Blockly.Msg.MIC_LITE_TWO_TIGERS = "两只老虎";
  Blockly.Msg.MIC_LITE_DORAEMON = "哆啦A梦";
  Blockly.Msg.MIC_LITE_LITTLE_APPLE = "小苹果";
  Blockly.Msg.MIC_LITE_NOTES_PLAY = "播放";
  Blockly.Msg.MIC_LITE_NOTES_PLAY_WAIT = "等待播完";
  Blockly.Msg.MIC_LITE_NOTES_STOP = "停止";
  Blockly.Msg.MIC_LITE_NOTES_LIGHT = "光线亮度";
  Blockly.Msg.MIC_LITE_NOTES_SOUND = "声音大小";
  Blockly.Msg.MIC_LITE_NOTES_SPEED = "%1 加速度";
  Blockly.Msg.MIC_LITE_NOTES_SPEEDX = "X轴";
  Blockly.Msg.MIC_LITE_NOTES_SPEEDY = "Y轴";
  Blockly.Msg.MIC_LITE_NOTES_SPEEDZ = "Z轴";
  Blockly.Msg.MIC_CONTROL_UTIL = "直到";
  Blockly.Msg.MIC_MATH_NOT = "不成立";
  Blockly.Msg.MIC_MATH_CONNECT = "连接";
  Blockly.Msg.MIC_MATH_AND = "和";
  Blockly.Msg.MIC_MATH_CHARAT = "的第";
  Blockly.Msg.MIC_MATH_CHARAT_INDEX = "个字符";
  Blockly.Msg.MIC_MATH_CHARAT_LENGTH = "的字符数";
  Blockly.Msg.MIC_MATH_CHARAT_CONTAINS = "包含";
  Blockly.Msg.MIC_MATH_REMAINDER = "%1 除以 %2 的余数";
  Blockly.Msg.MIC_MATH_ABS = "绝对值";
  Blockly.Msg.MIC_MATH_FLOOR = "向下取整";
  Blockly.Msg.MIC_MATH_CEIL = "向上取整";
  Blockly.Msg.MIC_MATH_SQRT = "平方根";
  Blockly.Msg.MIC_MATH_LOG = "In";
  Blockly.Msg.MIC_MATH_LOG10 = "log";
  Blockly.Msg.MIC_ARDUINO_DIGITAL_WRITE = "设引脚";
  Blockly.Msg.MIC_ARDUINO_DIGITAL_WRITE_FOR = "为";
  Blockly.Msg.MIC_ARDUINO_DIGITAL_READ = "读数字引脚";
  Blockly.Msg.MIC_ARDUINO_DIGITAL_READ_BOOLEAN = "读模拟引脚";
  Blockly.Msg.MIC_ARDUINO_DIGITAL_READ_STRING = "字符串";
  Blockly.Msg.MIC_ARDUINO_DIGITAL_READ_STRING_TO = "到";
  Blockly.Msg.MIC_ARDUINO_NUMBER_CONVERT = "数字 %1 到字符串";
  Blockly.Msg.MIC_ARDUINO_MILLIS = "系统运行时间(毫秒)";
  Blockly.Msg.MIC_ARDUINO_SERIAL_READSTRING = "读取串口字符串";
  Blockly.Msg.MIC_ARDUINO_MAP = "将 %1 从 %2 - %3 映射到 %4 - %5";
  Blockly.Msg.MIC_ARDUINO_CONSTRAIN = "约束%1介于(最小值)%2和(最大值)%3之间";
  Blockly.Msg.MIC_ARDUINO_DIGITAL_READ_BOOLEAN_INPUT = "输入引脚";
  Blockly.Msg.MIC_ARDUINO_DIGITAL_READ_BOOLEAN_IS = "是";
  Blockly.Msg.MIC_ARDUINO_DIGITAL_PWM = "引脚";
  Blockly.Msg.MIC_ARDUINO_DIGITAL_VARIABLE = "定义变量";
  Blockly.Msg.MIC_ARDUINO_DIGITAL_TYPE = "类型";
  Blockly.Msg.MIC_ARDUINO_FOR_MADE = "使用";
  Blockly.Msg.MIC_ARDUINO_FOR_EACH = "从 %1到 %2 步长为%3";
  Blockly.Msg.MIC_ARDUINO_INTERVAL_DOING_NAME = "间隔执行 名字";
  Blockly.Msg.MIC_ARDUINO_INTERVAL_DOING = "间隔时间 %1 毫秒";
  Blockly.Msg.MIC_ARDUINO_SERIAL_BAUD = "串口波特率  %1";
  Blockly.Msg.MIC_ARDUINO_SERIAL_PRINT = "%1 换行";
  Blockly.Msg.MIC_ARDUINO_SERIAL_PRINT_TEXT = "串口输出";
  Blockly.Msg.MIC_ARDUINO_SERIAL_PRINT_OP0 = "不带";
  Blockly.Msg.MIC_ARDUINO_SERIAL_PRINT_OP1 = "带";
  Blockly.Msg.MIC_SENSOR_IR_RESET_RECEIVE = "红外接收恢复 接口";
  Blockly.Msg.MIC_SENSOR_JOYSTICK_UP = "上";
  Blockly.Msg.MIC_SENSOR_JOYSTICK_DOWN = "下";
  Blockly.Msg.MIC_SENSOR_JOYSTICK_LEFT = "左";
  Blockly.Msg.MIC_SENSOR_JOYSTICK_RIGHT = "右";
  Blockly.Msg.MIC_SENSOR_JOYSTICK_CENTER = "中央";
  Blockly.Msg.MIC_SENSOR_JOYSTICK_RELEASED = "已抬起";
  Blockly.Msg.MIC_SENSOR_JOYSTICK_PRESSED = "已按下";
  Blockly.Msg.MIC_SENSOR_JOYSTICK = "摇杆 接口 %1 方向 %2 状态 %3";
  Blockly.Msg.MIC_SENSOR_IR_CONTROLLER_PORT = "红外遥控 接口 ";
  Blockly.Msg.MIC_SENSOR_IR_CONTROLLER_BACK = "后退";
  Blockly.Msg.MIC_SENSOR_IR_CONTROLLER_PLAY_PAUSE = "播放／暂停";
  Blockly.Msg.MIC_SENSOR_IR_CONTROLLER_VOLUME_ADD = "音量 +";
  Blockly.Msg.MIC_SENSOR_IR_CONTROLLER_VOLUME_MINUS = "音量 -";
  Blockly.Msg.MIC_SENSOR_IR_CONTROLLER_MUTE = "静音";
  Blockly.Msg.MIC_SENSOR_IR_RECEIVE = "红外接收 接口";
  Blockly.Msg.MIC_SENSOR_IR_SEND = "红外发射 编码";
  Blockly.Msg.MIC_SENSOR_IR_SEND_TEXT0 = "值";
  Blockly.Msg.MIC_SENSOR_IR_SEND_BITE = "比特数";
  Blockly.Msg.MIC_DISPLAY_COLORLED_TRANSITION = "No. %1 从 %2 到 %3 持续 %4秒";
  Blockly.Msg.MIC_DISPLAY_COLORLED_TRANSITION_PORT = "LED彩灯 接口 ";
  Blockly.Msg.MIC_DISPLAY_COLORLED_COLOR = "No. %1 颜色 %2 ";

  Blockly.Msg.LEFT = '左';
  Blockly.Msg.RIGHT = '右';

  Blockly.Msg.ACTION_MOTORPLUS_SPEED = "电机 %1 速度 %2";
  Blockly.Msg.ACTION_MOTORPLUS_BRAKE = "电机 %1 停止";
  Blockly.Msg.ACTION_SERVO = "舵机接口 %1旋转到 %2度";
  Blockly.Msg.ACTION_SERVO_ROTATE = "舵机接口 %1 从 %2度 旋转到 %3度 持续时间 %4秒";

  Blockly.Msg.MICSHOW_RGB = "红 %1 绿 %2 蓝 %3";

}

export default LoadArduinoMsgHans;
