// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.zh.hant');

goog.require('Blockly.Msg');

const LoadArduinoMsgHant = () => {
  Blockly.Msg.ADD_COMMENT = "加入註解";
  Blockly.Msg.ARD_ANALOGREAD = "讀取模擬接口#";
  Blockly.Msg.ARD_ANALOGREAD_TIP = "返回0到1024中的一個值";
  Blockly.Msg.ARD_ANALOGWRITE = "設置模擬接口#";
  Blockly.Msg.ARD_ANALOGWRITE_TIP = "將0到255之間的一個模擬值寫入到特定的脈寬調製端口";
  Blockly.Msg.ARD_BUILTIN_LED = "設置內置LED燈";
  Blockly.Msg.ARD_BUILTIN_LED_TIP = "設置Arduino版上的內置LED燈狀態爲開或者關";
  Blockly.Msg.ARD_COMPONENT_WARN1 = "A %1 configuration block with the same %2 name must be added to use this block!"; // untranslated
  Blockly.Msg.ARD_DEFINE = "Define"; // untranslated
  Blockly.Msg.ARD_DIGITALREAD = "讀取數字接口#";
  Blockly.Msg.ARD_DIGITALREAD_TIP = "從一端口讀取數字值：高電平或低電平";
  Blockly.Msg.ARD_DIGITALWRITE = "設置數字接口#";
  Blockly.Msg.ARD_DIGITALWRITE_TIP = "將數字值高電平或低電平寫入特定端口";
  Blockly.Msg.ARD_FUN_RUN_LOOP = "CocoBlockly不斷執行:";
  Blockly.Msg.ARD_FUN_RUN_SETUP = "CocoBlockly先執行:";
  Blockly.Msg.ARD_FUN_RUN_TIP = "定義Arduino setup() 和 loop() 函數。";
  Blockly.Msg.ARD_HIGH = "高";
  Blockly.Msg.ARD_HIGHLOW_TIP = "Set a pin state logic High or Low."; // untranslated
  Blockly.Msg.ARD_LOW = "低";
  Blockly.Msg.ARD_MAP = "映射";
  Blockly.Msg.ARD_MAP_TIP = "Re-maps a number from [0-1024] to another."; // untranslated
  Blockly.Msg.ARD_MAP_VAL = "值從[0-";
  Blockly.Msg.ARD_NOTONE_PIN = "No tone"; // untranslated
  Blockly.Msg.ARD_NOTONE_PIN_TIP = "Stop generating a tone on a pin"; // untranslated
  Blockly.Msg.ARD_PIN_WARN1 = "Pin %1 is needed for %2 as pin %3. Already used as %4."; // untranslated
  Blockly.Msg.ARD_PULSEON = "脈衝從接口#";
  Blockly.Msg.ARD_PULSEREAD = "暂停生成声音 #";
  Blockly.Msg.ARD_PULSEREAD = "讀取";
  Blockly.Msg.ARD_PULSETIMEOUT = "超時時間：";
  Blockly.Msg.ARD_PULSETIMEOUT_MS = ""; // untranslated
  Blockly.Msg.ARD_PULSETIMEOUT_TIP = "測量所選接口上脈衝的持續時間，如果其在超時時間內";
  Blockly.Msg.ARD_PULSE_TIP = "測量所選接口上脈衝的持續時間";
  Blockly.Msg.ARD_PWMWRITE = "設置PWM接口#";
  Blockly.Msg.ARD_SERIAL_AVAILABLE = "avalible"; // untranslated
  Blockly.Msg.ARD_SERIAL_BPS = "比特/秒";
  Blockly.Msg.ARD_SERIAL_PRINT = "打印";
  Blockly.Msg.ARD_SERIAL_PRINT_NEWLINE = "添加新行";
  Blockly.Msg.ARD_SERIAL_PRINT_TIP = "將數據以可讀的ASCII文本形式打印到控制檯或串行端口";
  Blockly.Msg.ARD_SERIAL_PRINT_WARN = "Serial相關的初始化積木需要被添加";
  Blockly.Msg.ARD_SERIAL_READ = "讀取";
  Blockly.Msg.ARD_SERIAL_SETUP = "設置";
  Blockly.Msg.ARD_SERIAL_SETUP_TIP = "選擇特定的串行外設的速度";
  Blockly.Msg.ARD_SERIAL_SPEED = "速度爲";
  Blockly.Msg.ARD_SERIAL_WRITE = "寫出";
  Blockly.Msg.ARD_SERVO_READ = "讀取舵機信息，設置接口爲PIN#";
  Blockly.Msg.ARD_SERVO_READ_TIP = "讀取舵機的角度";
  Blockly.Msg.ARD_SERVO_SETUP = "舵機初始化";
  Blockly.Msg.ARD_SERVO_WRITE = "定義舵機接口爲";
  Blockly.Msg.ARD_SERVO_WRITE_DEG_180 = "度 (0~180)";
  Blockly.Msg.ARD_SERVO_WRITE_TIP = "設置舵機轉動一定的角度";
  Blockly.Msg.ARD_SERVO_WRITE_TO = "設置其轉動角度爲";
  Blockly.Msg.ARD_SPI_SETUP = "設置";
  Blockly.Msg.ARD_SPI_SETUP_CONF = "配置";
  Blockly.Msg.ARD_SPI_SETUP_DIVIDE = "時鐘分頻";
  Blockly.Msg.ARD_SPI_SETUP_LSBFIRST = "LSBFIRST"; // untranslated
  Blockly.Msg.ARD_SPI_SETUP_MODE = "SPI模式（空 - 邊界）";
  Blockly.Msg.ARD_SPI_SETUP_MODE0 = "0 (Low - Falling)"; // untranslated
  Blockly.Msg.ARD_SPI_SETUP_MODE1 = "1 (Low - Rising)"; // untranslated
  Blockly.Msg.ARD_SPI_SETUP_MODE2 = "2 (High - Falling)"; // untranslated
  Blockly.Msg.ARD_SPI_SETUP_MODE3 = "3 (High - Rising)"; // untranslated
  Blockly.Msg.ARD_SPI_SETUP_MSBFIRST = "MSBFIRST"; // untranslated
  Blockly.Msg.ARD_SPI_SETUP_SHIFT = "數據傳輸";
  Blockly.Msg.ARD_SPI_SETUP_TIP = "配置SPI外設";
  Blockly.Msg.ARD_SPI_TRANSRETURN_TIP = "Send a SPI message to an specified slave device and get data back."; // untranslated
  Blockly.Msg.ARD_SPI_TRANS_NONE = "none"; // untranslated
  Blockly.Msg.ARD_SPI_TRANS_SLAVE = "來控制接口";
  Blockly.Msg.ARD_SPI_TRANS_TIP = "Send a SPI message to an specified slave device."; // untranslated
  Blockly.Msg.ARD_SPI_TRANS_VAL = "轉換";
  Blockly.Msg.ARD_SPI_TRANS_WARN1 = "A setup block for %1 must be added to the workspace to use this block!"; // untranslated
  Blockly.Msg.ARD_SPI_TRANS_WARN2 = "Old pin value %1 is no longer available."; // untranslated
  Blockly.Msg.ARD_STEPPER_COMPONENT = "stepper"; // untranslated
  Blockly.Msg.ARD_STEPPER_DEFAULT_NAME = "MyStepper"; // untranslated
  Blockly.Msg.ARD_STEPPER_MOTOR = "步進馬達";
  Blockly.Msg.ARD_STEPPER_PIN1 = "接口1#'：";
  Blockly.Msg.ARD_STEPPER_PIN2 = "接口2#'：";
  Blockly.Msg.ARD_STEPPER_REVOLVS = "每轉有多少步：";
  Blockly.Msg.ARD_STEPPER_SETUP = "設置步進馬達名爲：";
  Blockly.Msg.ARD_STEPPER_SETUP_TIP = "配置步進馬達接口排列和其他設置";
  Blockly.Msg.ARD_STEPPER_SPEED = "設定轉速（轉/分）爲";
  Blockly.Msg.ARD_STEPPER_STEP = "移動步進馬達";
  Blockly.Msg.ARD_STEPPER_STEPS = "步";
  Blockly.Msg.ARD_STEPPER_STEP_TIP = "將步進馬達轉動一定數量的步數";
  Blockly.Msg.ARD_TIME_CHRONO_CHECK = "當碼錶停至";
  Blockly.Msg.ARD_TIME_CHRONO_CHECK1 = "毫秒時";
  Blockly.Msg.ARD_TIME_CHRONO_ELAPSED = "碼錶已過去的時間";
  Blockly.Msg.ARD_TIME_CHRONO_RESET = "重置碼錶";
  Blockly.Msg.ARD_TIME_CHRONO_SETUP = "碼錶初始化";
  Blockly.Msg.ARD_TIME_DELAY = "等待";
  Blockly.Msg.ARD_TIME_DELAY_MICROS = "微秒";
  Blockly.Msg.ARD_TIME_DELAY_MICRO_TIP = "等待一定的時間（以微秒爲單位）";
  Blockly.Msg.ARD_TIME_DELAY_TIP = "等待一定的時間（以毫秒爲單位）";
  Blockly.Msg.ARD_TIME_DO = "執行";
  Blockly.Msg.ARD_TIME_DO_MS = "執行";
  Blockly.Msg.ARD_TIME_EVERY = "每隔";
  Blockly.Msg.ARD_TIME_EVERY_MS = "每隔";
  Blockly.Msg.ARD_TIME_INF = "永久等待（結束程序）";
  Blockly.Msg.ARD_TIME_INF_TIP = "無限期等待，即停止程序";
  Blockly.Msg.ARD_TIME_MICROS = "當前已過時間（微秒）";
  Blockly.Msg.ARD_TIME_MICROS_TIP = "返回自Arduino版開始執行當前程序以來的微秒數，必須以長整數型儲存";
  Blockly.Msg.ARD_TIME_MILLIS = "當前已過時間（毫秒）";
  Blockly.Msg.ARD_TIME_MILLIS_TIP = "返回自Arduino版開始執行當前程序以來的毫秒數，必須以長整數型儲存";
  Blockly.Msg.ARD_TIME_MS = "毫秒";
  Blockly.Msg.ARD_TIME_SECOND = "秒";
  Blockly.Msg.ARD_TIME_SECOND_MS = "毫秒";
  Blockly.Msg.ARD_TONE_FREQ = "frequency"; // untranslated
  Blockly.Msg.ARD_TONE_PIN = "Tone PIN#"; // untranslated
  Blockly.Msg.ARD_TONE_PIN_TIP = "Generate audio tones on a pin"; // untranslated
  Blockly.Msg.ARD_TYPE_ARRAY = "Array"; // untranslated
  Blockly.Msg.ARD_TYPE_BOOL = "Boolean"; // untranslated
  Blockly.Msg.ARD_TYPE_CHAR = "Character"; // untranslated
  Blockly.Msg.ARD_TYPE_CHILDBLOCKMISSING = "ChildBlockMissing"; // untranslated
  Blockly.Msg.ARD_TYPE_DECIMAL = "Decimal"; // untranslated
  Blockly.Msg.ARD_TYPE_LONG = "Large Number"; // untranslated
  Blockly.Msg.ARD_TYPE_NULL = "Null"; // untranslated
  Blockly.Msg.ARD_TYPE_NUMBER = "Number"; // untranslated
  Blockly.Msg.ARD_TYPE_SHORT = "Short Number"; // untranslated
  Blockly.Msg.ARD_TYPE_TEXT = "Text"; // untranslated
  Blockly.Msg.ARD_TYPE_UNDEF = "Undefined"; // untranslated
  Blockly.Msg.ARD_VAR_AS = "爲";
  Blockly.Msg.ARD_VAR_AS_TIP = "Sets a value to a specific type"; // untranslated
  Blockly.Msg.ARD_WRITE_TO = "爲";
  Blockly.Msg.AUTH = "請授權這個應用程式以保存您的作品並共享。";
  Blockly.Msg.BASIC_AS = "as"; // untranslated
  Blockly.Msg.BASIC_BLACK_OUT = "Black out"; // untranslated
  Blockly.Msg.BASIC_BRTN = "Brightness"; // untranslated
  Blockly.Msg.BASIC_BUZZER_PLAY = "Buzzer plays "; // untranslated
  Blockly.Msg.BASIC_BUZZER_SETUP = "Buzzer Setup"; // untranslated
  Blockly.Msg.BASIC_COUNTER_SETTING = "按钮為";
  Blockly.Msg.BASIC_COUNTER_SETUP = "設置一个計數器 ";
  Blockly.Msg.BASIC_FOR = "for"; // untranslated
  Blockly.Msg.BASIC_FROM = "from"; // untranslated
  Blockly.Msg.BASIC_HZ = "Hz"; // untranslated
  Blockly.Msg.BASIC_IF_SWITCH = "If switch "; // untranslated
  Blockly.Msg.BASIC_IS = " is "; // untranslated
  Blockly.Msg.BASIC_LIGHT_PIN = "Light Pin#"; // untranslated
  Blockly.Msg.BASIC_LIGHT_WARNING = "亮度值必須在0到255之間";
  Blockly.Msg.BASIC_MUTE = "Mute"; // untranslated
  Blockly.Msg.BASIC_NOLED = "關閉在接口%1上的燈光";
  Blockly.Msg.BASIC_NOTONE = "關閉在接口%1上的音調";
  Blockly.Msg.BASIC_NOTONE_TIP = "關閉所選接口上的音調輸出";
  Blockly.Msg.BASIC_PIN_NUM = "Pin#"; // untranslated
  Blockly.Msg.BASIC_READBUTTON = "讀取在接口%1上開關的狀態";
  Blockly.Msg.BASIC_READCOUNTER = "讀取計數器的数值 計數按钮為%1";
  Blockly.Msg.BASIC_READKNOB = "讀取在接口%1上電位器的數值";
  Blockly.Msg.BASIC_SET = "Set"; // untranslated
  Blockly.Msg.BASIC_SETANALOGLED = "設置在接口%1上的燈光亮度為%2";
  Blockly.Msg.BASIC_SETDIGITALLED = "打開在接口%1上的燈光";
  Blockly.Msg.BASIC_SETTONE = "設置在接口%1上的音調頻率為%2";
  Blockly.Msg.BASIC_SET_PIN = "Set Pin#"; // untranslated
  Blockly.Msg.BASIC_TO = "to"; // untranslated
  Blockly.Msg.BASIC_TONE_TIP = "設置接口上的音調頻率爲31到65535中某個特定頻率";
  Blockly.Msg.BASIC_TONE_WARNING = "頻率值必須在31到65535之間";
  Blockly.Msg.BLUE = "藍";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_DATA = "data";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVEMSG = "接收數據";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVEMSG_ISSUCCESS = "接收數據成功";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVE_GET_LINE2 = "獲取第";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVE_GET_LINE2_2 = "位的數據";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVE_GET_LINE3 = "位的数据，并设置类型为";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVE_GET_LINE4 = "";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_RECEIVE_LINE3 = "長度為";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_SENDMSG = "發送數據";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_SETUP = "藍牙对藍牙通信";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_SETUP1 = "对藍牙通信";
  Blockly.Msg.BLUETOOTH_INTERCOMMS_SETUP2 = "初始化";
  Blockly.Msg.BLUETOOTH_LIST_RECEIVED = "已接收到的數組";
  Blockly.Msg.BLUETOOTH_LIST_RECEIVED1 = "中第";
  Blockly.Msg.BLUETOOTH_LIST_RECEIVED2 = "位的值";
  Blockly.Msg.BLUETOOTH_NUMBER_RECEIVED = "已接收到的數字";
  Blockly.Msg.BLUETOOTH_PAIRING_BIND_ADDR = "綁定從屬裝置地址:";
  Blockly.Msg.BLUETOOTH_PAIRING_MASTER = "藍牙配對: 設置為主機裝置";
  Blockly.Msg.BLUETOOTH_PAIRING_SETTING_BAUDRATE = "設置波特率:";
  Blockly.Msg.BLUETOOTH_PAIRING_SETTING_TIMEOUT = "設置延時:";
  Blockly.Msg.BLUETOOTH_PAIRING_SLAVE = "藍牙配對: 設置為從屬裝置";
  Blockly.Msg.BLUETOOTH_SETUP = "儅藍牙接收到";
  Blockly.Msg.BLUETOOTH_SETUP_DO = "并且做";
  Blockly.Msg.BLUETOOTH_SETUP_LIST_SETTING = "長度為";
  Blockly.Msg.BLUETOOTH_SETUP_OPT1 = "一串文字";
  Blockly.Msg.BLUETOOTH_SETUP_OPT2 = "一個數字";
  Blockly.Msg.BLUETOOTH_SETUP_OPT3 = "一個數組";
  Blockly.Msg.BLUETOOTH_SETUP_SET = "設置";
  Blockly.Msg.BLUETOOTH_SETUP_TO = "為接收到的信息";
  Blockly.Msg.BLUETOOTH_TEXT_RECEIVED = "已接收到的字符串";
  Blockly.Msg.BLYNK_AUTH = "認證密匙: ";
  Blockly.Msg.BLYNK_CONNECT = "當Blynk連接成功";
  Blockly.Msg.BLYNK_CREATE_WITH_CONTAINER_TITLE_ADD = "Data";
  Blockly.Msg.BLYNK_CREATE_WITH_ITEM_TITLE = "item";
  Blockly.Msg.BLYNK_DATA = "data";
  Blockly.Msg.BLYNK_GET_DATANAME = "從";
  Blockly.Msg.BLYNK_GET_DATANAME1 = "獲得";
  Blockly.Msg.BLYNK_GET_DATANAME2 = "數據";
  Blockly.Msg.BLYNK_GET_INDEX = "第";
  Blockly.Msg.BLYNK_GET_INDEX1 = "位的數據";
  Blockly.Msg.BLYNK_GET_OF = "獲得數據";
  Blockly.Msg.BLYNK_GET_OF1 = "獲得";
  Blockly.Msg.BLYNK_GET_OF2 = "的數據";
  Blockly.Msg.BLYNK_GPS_ALTITUDE = "高度(海拔)";
  Blockly.Msg.BLYNK_GPS_LATITUDE = "緯度";
  Blockly.Msg.BLYNK_GPS_LONGITUDE = "經度";
  Blockly.Msg.BLYNK_GPS_SPEED = "速度";
  Blockly.Msg.BLYNK_LOG = "BLYNK_LOG";
  Blockly.Msg.BLYNK_PW = "WiFi密碼: ";
  Blockly.Msg.BLYNK_READ = "當Blynk請求";
  Blockly.Msg.BLYNK_READ1 = "數據";
  Blockly.Msg.BLYNK_SELECT = "選擇";
  Blockly.Msg.BLYNK_SETUP = "BLYNK初始化";
  Blockly.Msg.BLYNK_SSID = "WiFi名稱: ";
  Blockly.Msg.BLYNK_TIME_DO = "執行";
  Blockly.Msg.BLYNK_TIME_SECOND = "秒";
  Blockly.Msg.BLYNK_TIME_SETTING = "设置計時器: 每隔";
  Blockly.Msg.BLYNK_VIRTUALWRITE = "發送數據到";
  Blockly.Msg.BLYNK_VIRTUALWRITE_DATA = "Data:";
  Blockly.Msg.BLYNK_WIFI = "連接WiFi網絡";
  Blockly.Msg.BLYNK_WRITE = "從";
  Blockly.Msg.BLYNK_WRITE1 = "獲取數據";
  Blockly.Msg.BLYNK_WRITE_VARIABLE = "存到";
  Blockly.Msg.BLYNK_WRITE_VARLENGTH = "長度";
  Blockly.Msg.CHANGE_VALUE_TITLE = "修改值:";
  Blockly.Msg.CHAT = "與您的合作者洽談藉由在此框輸入！";
  Blockly.Msg.CLEAN_UP = "整理積木";
  Blockly.Msg.CLOUDDATA_CREATE_WITH_CONTAINER_TITLE_ADD = "key[]";
  Blockly.Msg.CLOUDDATA_CREATE_WITH_INPUT_WITH = "添加";
  Blockly.Msg.CLOUDDATA_CREATE_WITH_ITEM_TITLE = "value";
  Blockly.Msg.CLOUDDATA_GENERATOR_DATA = "生成數據";
  Blockly.Msg.CLOUDDATA_PARSE_JSON = "的數據從";
  Blockly.Msg.CLOUDDATA_PARSE_KEY = "解析得到名爲";
  Blockly.Msg.CLOUDDATA_PARSE_PRETTYPRINT_DISPLAY = "獲得生成的數據";
  Blockly.Msg.CLOUDDATA_PARSE_SETUP_INIT = "數據解析初始化為";
  Blockly.Msg.CLOUDDATA_PARSE_SETUP_PAYLOAD = "解析内容";
  Blockly.Msg.CLOUDDATA_PARSE_TYPE = "類型爲";
  Blockly.Msg.COCOCLOUD_CREATE_WITH_CONTAINER_TITLE_ADD = "LIST";
  Blockly.Msg.COCOCLOUD_CREATE_WITH_ITEM_TITLE = "Event";
  Blockly.Msg.COCOCLOUD_GET = "向項目";
  Blockly.Msg.COCOCLOUD_GET1 = "獲取數據";
  Blockly.Msg.COCOCLOUD_GETPAYLOAD = "從項目獲取到的數據";
  Blockly.Msg.COCOCLOUD_POST = "發送到項目";
  Blockly.Msg.COCOCLOUD_POST_DATA = "數據";
  Blockly.Msg.COCOCLOUD_TIME_DAY = "日";
  Blockly.Msg.COCOCLOUD_TIME_GETDATE = "獲取";
  Blockly.Msg.COCOCLOUD_TIME_GETTIME = "獲取";
  Blockly.Msg.COCOCLOUD_TIME_HOUR = "時";
  Blockly.Msg.COCOCLOUD_TIME_MINUTE = "分";
  Blockly.Msg.COCOCLOUD_TIME_MONTH = "月份";
  Blockly.Msg.COCOCLOUD_TIME_SECOND = "秒";
  Blockly.Msg.COCOCLOUD_TIME_SETUP = "世界時間";
  Blockly.Msg.COCOCLOUD_TIME_YEAR = "年份";
  Blockly.Msg.COCOCLOUD_TITLE = "Web服務 CocoCloud";
  Blockly.Msg.COLLAPSE_ALL = "收合積木";
  Blockly.Msg.COLLAPSE_BLOCK = "收合積木";
  Blockly.Msg.COLOR = "顔色";
  Blockly.Msg.COLORANALYZER_SETUP = "顔色分析設置";
  Blockly.Msg.COLOUR_BLEND_COLOUR1 = "顏色 1";
  Blockly.Msg.COLOUR_BLEND_COLOUR2 = "顏色 2";
  Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/"; // untranslated
  Blockly.Msg.COLOUR_BLEND_RATIO = "比例";
  Blockly.Msg.COLOUR_BLEND_TITLE = "混合";
  Blockly.Msg.COLOUR_BLEND_TOOLTIP = "透過一個比率 (0.0-1.0)來混合兩種顏色。";
  Blockly.Msg.COLOUR_PICKER_HELPURL = "https://zh.wikipedia.org/wiki/顏色";
  Blockly.Msg.COLOUR_PICKER_TOOLTIP = "從調色板中選擇一種顏色。";
  Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com"; // untranslated
  Blockly.Msg.COLOUR_RANDOM_TITLE = "隨機顏色";
  Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "隨機選擇一種顏色。";
  Blockly.Msg.COLOUR_RGB_BLUE = "藍";
  Blockly.Msg.COLOUR_RGB_GREEN = "綠";
  Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html"; // untranslated
  Blockly.Msg.COLOUR_RGB_RED = "紅";
  Blockly.Msg.COLOUR_RGB_TITLE = "顏色";
  Blockly.Msg.COLOUR_RGB_TOOLTIP = "透過指定紅、綠、 藍色的值來建立一種顏色。所有的值必須介於 0 和 100 之間。";
  Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks"; // untranslated
  Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "停止 迴圈";
  Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "繼續下一個 迴圈";
  Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "離開當前的 迴圈";
  Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "跳過這個迴圈的其餘步驟，並繼續下一次的迴圈運算。";
  Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "警告： 此積木僅可用於迴圈內。";
  Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each"; // untranslated
  Blockly.Msg.CONTROLS_FOREACH_TITLE = "取出每個 %1 自列表 %2";
  Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "遍歷每個列表中的項目，將變數 '%1' 設定到該項目中，然後執行某些語句";
  Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with"; // untranslated
  Blockly.Msg.CONTROLS_FOR_TITLE = "使用 %1 從範圍 %2 到 %3 每隔 %4";
  Blockly.Msg.CONTROLS_FOR_TOOLTIP = "從起始數到結尾數中取出變數 \"%1\" 的值，按指定的時間間隔，執行指定的積木。";
  Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "將條件添加到'如果'積木。";
  Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "加入一個最終，所有條件下都都執行的區塊到'如果'積木中";
  Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse"; // untranslated
  Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "添加、 刪除或重新排列各區塊來此重新配置這個'如果'積木。";
  Blockly.Msg.CONTROLS_IF_MSG_ELSE = "否則";
  Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "否則如果";
  Blockly.Msg.CONTROLS_IF_MSG_IF = "如果";
  Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "當值為真時，執行一些語句";
  Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "當值為真時，執行第一個語句，否則則執行第二個語句";
  Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "如果第一個值為真，則執行第一個語句。否則當第二個值為真時，則執行第二個語句";
  Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "如果第一個值為真，則執行第一個語句。否則當第二個值為真時，則執行第二個語句。如果前幾個敘述都不為真，則執行最後一個語句";
  Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://zh.wikipedia.org/wiki/For迴圈";
  Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "執行";
  Blockly.Msg.CONTROLS_REPEAT_TITLE = "重複 %1 次";
  Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "多次執行一些語句";
  Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat"; // untranslated
  Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "重複 直到";
  Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "重複 當";
  Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "當值為否時，執行一些語句";
  Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "當值為真時，執行一些語句";
  Blockly.Msg.DELETE_ALL_BLOCKS = "刪除共 %1 塊積木？";
  Blockly.Msg.DELETE_BLOCK = "刪除積木";
  Blockly.Msg.DELETE_X_BLOCKS = "刪除 %1 塊積木";
  Blockly.Msg.DISABLE_BLOCK = "停用積木";
  Blockly.Msg.DUPLICATE_BLOCK = "複製";
  Blockly.Msg.ENABLE_BLOCK = "啟用積木";
  Blockly.Msg.ENCODER_GETROTATIONSPEED = "讀取碼盤數值";
  Blockly.Msg.ENCODER_SETUP = "碼盤初始化·";
  Blockly.Msg.ENCODER_SETUP_1 = "設定中斷引脚";
  Blockly.Msg.ENV_AS = "as"; // untranslated
  Blockly.Msg.ENV_BLUE_PIN = "藍 從接口";
  Blockly.Msg.ENV_BUZZER_ALARM = "Buzzer Alarm"; // untranslated
  Blockly.Msg.ENV_CRITICAL_VAL = "When the critical value of"; // untranslated
  Blockly.Msg.ENV_DO = "Do"; // untranslated
  Blockly.Msg.ENV_GREEN_PIN = "綠 從接口";
  Blockly.Msg.ENV_REACHES = "reaches"; // untranslated
  Blockly.Msg.ENV_RED_PIN = "紅 從接口 ";
  Blockly.Msg.ENV_SENSOR_HUMID = "讀取湿度的數值從接口 ";
  Blockly.Msg.ENV_SENSOR_HUMIDITY = "濕度";
  Blockly.Msg.ENV_SENSOR_LIGHT = "讀取光照的数值從接口 ";
  Blockly.Msg.ENV_SENSOR_MIC = "讀取聲音的數值從接口 ";
  Blockly.Msg.ENV_SENSOR_READ = "讀取數值從";
  Blockly.Msg.ENV_SENSOR_READTEMP = "讀取溫度的數值從接口 ";
  Blockly.Msg.ENV_SENSOR_SET_RGB = "設置RGB燈光";
  Blockly.Msg.ENV_SENSOR_SOUND = "聲音";
  Blockly.Msg.ENV_SENSOR_TEMPUNIT = "設置單位為";
  Blockly.Msg.ENV_SENSOR_UNITC = "攝氏度";
  Blockly.Msg.ENV_SENSOR_UNITF = "華氏度";
  Blockly.Msg.ENV_SET = "Set"; // untranslated
  Blockly.Msg.ENV_SETRGB_B = "藍 從接口";
  Blockly.Msg.ENV_SETRGB_G = "綠 從接口";
  Blockly.Msg.ENV_SETRGB_R = "紅 從接口 ";
  Blockly.Msg.ENV_SETUP = "環境感應設置";
  Blockly.Msg.ENV_SET_TEMP = "Set temperature as "; // untranslated
  Blockly.Msg.ENV_SET_TEMP_UNIT = "Set unit as "; // untranslated
  Blockly.Msg.EXPAND_ALL = "展開積木";
  Blockly.Msg.EXPAND_BLOCK = "展開積木";
  Blockly.Msg.EXPORTPNG = "導出PNG快照";
  Blockly.Msg.EXPORTXML = "導出XML文件";
  Blockly.Msg.EXTERNAL_INPUTS = "多行輸入";
  Blockly.Msg.Friday = "周五";
  Blockly.Msg.GPS_LATITUDE = "獲取緯度";
  Blockly.Msg.GPS_LONGITUDE = "獲取經度";
  Blockly.Msg.GPS_SETUP = "GPS 初始化";
  Blockly.Msg.GREEN = "綠";
  Blockly.Msg.HELP = "說明";
  Blockly.Msg.HID_KEYBOARD_PRESS = "設置鍵盤: 按下";
  Blockly.Msg.HID_KEYBOARD_RELEASE = "設置鍵盤: 釋放";
  Blockly.Msg.HID_KEYBOARD_RELEASEALL = "設置鍵盤: 釋放全部";
  Blockly.Msg.HID_MOUSE_CLICK = "設置鼠標: 點擊";
  Blockly.Msg.HID_MOUSE_CLICK_LEFT = "左鍵";
  Blockly.Msg.HID_MOUSE_CLICK_RIGHT = "右鍵";
  Blockly.Msg.HID_MOUSE_MOVE = "設置鼠標: 向";
  Blockly.Msg.HID_MOUSE_MOVE_DISTANCE = "px";
  Blockly.Msg.HID_MOUSE_MOVE_FOR = "移動";
  Blockly.Msg.HID_MOUSE_PRESS = "設置鼠標: 按下";
  Blockly.Msg.HID_MOUSE_RELEASE = "設置鼠標: 鬆開";
  Blockly.Msg.HID_SETUP = "HID初始化";
  Blockly.Msg.INFRAREDRAY_RECVAL = "接收值";
  Blockly.Msg.INFRAREDRAY_SETUP = "紅外綫接收器設置";
  Blockly.Msg.INLINE_INPUTS = "單行輸入";
  Blockly.Msg.ISCOLOR = "是否颜色";
  Blockly.Msg.JSONOBJECT_CREATE = "JSON Object"; // untranslated
  Blockly.Msg.JSONTOOL_ARRAY_SIZE = "數組大小";
  Blockly.Msg.JSONTOOL_GENERATOR = "JSON構造器 ";
  Blockly.Msg.JSONTOOL_GENERATOR_ARRAY_VALUE = "JSON數組加入: value";
  Blockly.Msg.JSONTOOL_GENERATOR_JSONOBJECT = "Object";
  Blockly.Msg.JSONTOOL_GENERATOR_KEY = "JSON对象加入：Key ";
  Blockly.Msg.JSONTOOL_GENERATOR_MAIN_JSONNAME = "JSONVar";
  Blockly.Msg.JSONTOOL_GENERATOR_MAIN_TITLE = "生成JSON";
  Blockly.Msg.JSONTOOL_GENERATOR_MAIN_TITLE_NAME = "命名为";
  Blockly.Msg.JSONTOOL_GENERATOR_NESTED_TITLE = "嵌套JSON";
  Blockly.Msg.JSONTOOL_GENERATOR_NESTED_TITLE_NAME = "命名为";
  Blockly.Msg.JSONTOOL_GENERATOR_SETUP = "JSON構造器初始化";
  Blockly.Msg.JSONTOOL_GENERATOR_VALUE = "Value";
  Blockly.Msg.JSONTOOL_OBJECT_SIZE = "对象大小";
  Blockly.Msg.JSONTOOL_PARSE_ARRAY = "(JSON數組)";
  Blockly.Msg.JSONTOOL_PARSE_BY = "獲取";
  Blockly.Msg.JSONTOOL_PARSE_EACH = "从JSON对象";
  Blockly.Msg.JSONTOOL_PARSE_INDEX = "下標为";
  Blockly.Msg.JSONTOOL_PARSE_ISSUCCESS = "是否成功解析";
  Blockly.Msg.JSONTOOL_PARSE_ISSUCCESS_NAME = "对于JSON对象";
  Blockly.Msg.JSONTOOL_PARSE_JSONOBJECT = "Object";
  Blockly.Msg.JSONTOOL_PARSE_KEY = "(JSON对象)key";
  Blockly.Msg.JSONTOOL_PARSE_KEYVALUE = "从JSON Object %1 获得key %2 的值";
  Blockly.Msg.JSONTOOL_PARSE_NEST = "内嵌";
  Blockly.Msg.JSONTOOL_PARSE_PRETTYPRINT = "打印 JSON ";
  Blockly.Msg.JSONTOOL_PARSE_PRETTYPRINT_DISPLAY = "規範化數據r";
  Blockly.Msg.JSONTOOL_PARSE_PRETTYPRINT_WAY = "按規範方式";
  Blockly.Msg.JSONTOOL_PARSE_RESPONSE = "數據内容";
  Blockly.Msg.JSONTOOL_PARSE_SETUP = "JSON解析器初始化";
  Blockly.Msg.JSONTOOL_PARSE_TOVAR = "獲取數據到";
  Blockly.Msg.JSONTOOL_PARSE_VARTYPE = "";
  Blockly.Msg.LED_BACKCOLOR = "背景";
  Blockly.Msg.LED_BRIGHTNESS_WARNING = "亮度應該在範圍 0 - 255 之間";
  Blockly.Msg.LED_BRTN = "亮度";
  Blockly.Msg.LED_CLEAR = "清除";
  Blockly.Msg.LED_COLOR = "顔色";
  Blockly.Msg.LED_COORDINATE = "坐標";
  Blockly.Msg.LED_DRAW = "畫";
  Blockly.Msg.LED_FONT = "字體";
  Blockly.Msg.LED_FULL = "實心";
  Blockly.Msg.LED_HEIGHT = "高";
  Blockly.Msg.LED_LINE = "線";
  Blockly.Msg.LED_LINE_END = "終點";
  Blockly.Msg.LED_LINE_START = "起點";
  Blockly.Msg.LED_MULTICOM = "H"; // untranslated
  Blockly.Msg.LED_PANELHEIGHT = "高(拼接個數)";
  Blockly.Msg.LED_PANELWIDTH = "寬(拼接個數)";
  Blockly.Msg.LED_PATTERN = "圖形";
  Blockly.Msg.LED_PIN = "接口";
  Blockly.Msg.LED_PIXEL = "點";
  Blockly.Msg.LED_POSITION = "位置";
  Blockly.Msg.LED_RECTANGLE = "矩形";
  Blockly.Msg.LED_SCROLL = "滾動";
  Blockly.Msg.LED_SCROLL_NO = "否";
  Blockly.Msg.LED_SCROLL_SPEED = "速度";
  Blockly.Msg.LED_SCROLL_YES = "是";
  Blockly.Msg.LED_SETUP = "LED燈組設置";
  Blockly.Msg.LED_SET_BRIGHTNESS = "設置亮度為";
  Blockly.Msg.LED_SET_ROTATION = "將熒幕旋轉至";
  Blockly.Msg.LED_SET_ROTATION_DEGREE = "度";
  Blockly.Msg.LED_SHOW_ALL = "顯示圖案";
  Blockly.Msg.LED_SINGLE_SETUP = "單個LED燈組設置";
  Blockly.Msg.LED_SIZE = "大小";
  Blockly.Msg.LED_STRIP_LOCATION = "位置";
  Blockly.Msg.LED_STRIP_PIXEL = "繪製像素";
  Blockly.Msg.LED_STROKED = "空心";
  Blockly.Msg.LED_TEXT = "文本";
  Blockly.Msg.LED_WIDTH = "寬";
  Blockly.Msg.LED_WORD = "單字";
  Blockly.Msg.LIGHT_BRIGHTNESS = "上的燈光亮度為：";
  Blockly.Msg.LIGHT_PIN = "設置";
  Blockly.Msg.LIGHT_TURNOFF = "關閉燈光輸出在";
  Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list"; // untranslated
  Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "建立空列表";
  Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "返回一個長度為 0 的列表，不包含任何資料記錄";
  Blockly.Msg.LISTS_CREATE_LIST_WITH = "創建數组";
  Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "列表";
  Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "添加、 刪除或重新排列各區塊來此重新配置這個 列表 積木。";
  Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with"; // untranslated
  Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "將一個項目加入到列表中。";
  Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "建立一個具備任意數量項目的列表。";
  Blockly.Msg.LISTS_GETINDEX = "从數组 %1 中獲取第 %2 位的值";
  Blockly.Msg.LISTS_GET_INDEX_FIRST = "第一筆";
  Blockly.Msg.LISTS_GET_INDEX_FROM_END = "倒數第#筆";
  Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#"; // untranslated
  Blockly.Msg.LISTS_GET_INDEX_GET = "取值";
  Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "取出並移除";
  Blockly.Msg.LISTS_GET_INDEX_LAST = "最後一筆";
  Blockly.Msg.LISTS_GET_INDEX_RANDOM = "隨機";
  Blockly.Msg.LISTS_GET_INDEX_REMOVE = "移除";
  Blockly.Msg.LISTS_GET_INDEX_TAIL = ""; // untranslated
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "返回列表中的第一個項目";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "返回在列表中的指定位置的項目。#1 是最後一個項目。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "返回在列表中的指定位置的項目。#1 是第一個項目。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "返回列表中的最後一個項目";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "返回列表中隨機的一個項目";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "移除並返回列表中的第一個項目";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "移除並返回列表中的指定位置的項目。#1 是最後一個項目。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "移除並返回列表中的指定位置的項目。#1 是第一個項目。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "移除並返回列表中的最後一個項目";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "移除並返回列表中的隨機一個項目";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "移除列表中的第一個項目";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "移除在列表中的指定位置的項目。#1 是最後一個項目。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "移除在列表中的指定位置的項目。#1 是第一個項目。";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "移除列表中的最後一個項目";
  Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "移除列表中隨機的一個項目";
  Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "到 倒數 # 位";
  Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "到 #";
  Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "到 最後";
  Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist"; // untranslated
  Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "從 頭 取得子列表";
  Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "從倒數 # 取得子列表";
  Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "從 # 取得子列表";
  Blockly.Msg.LISTS_GET_SUBLIST_TAIL = ""; // untranslated
  Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "複製列表中指定的部分。";
  Blockly.Msg.LISTS_INDEX_OF_FIRST = "找出 第一個 項目出現";
  Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list"; // untranslated
  Blockly.Msg.LISTS_INDEX_OF_LAST = "找出 最後一個 項目出現";
  Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "返回在列表中的第一個/最後一個匹配項目的索引值。如果未找到則返回 0。";
  Blockly.Msg.LISTS_INLIST = "自列表";
  Blockly.Msg.LISTS_INT_CREATE_WITH_INPUT_WITH = "使用這些值建立數字列表";
  Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty"; // untranslated
  Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 值為空";
  Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "如果該列表為空，則返回 真。";
  Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of"; // untranslated
  Blockly.Msg.LISTS_LENGTH_TITLE = "長度 %1";
  Blockly.Msg.LISTS_LENGTH_TOOLTIP = "返回列表的長度。";
  Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with"; // untranslated
  Blockly.Msg.LISTS_REPEAT_TITLE = "建立列表使用項目 %1 重複 %2 次數";
  Blockly.Msg.LISTS_REPEAT_TOOLTIP = "建立包含指定重複次數的 值 的列表。";
  Blockly.Msg.LISTS_SETINDEX = "賦值 %1 中第 %2 位的值到 %3";
  Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set"; // untranslated
  Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "為";
  Blockly.Msg.LISTS_SET_INDEX_INSERT = "插入在";
  Blockly.Msg.LISTS_SET_INDEX_SET = "設定";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "在列表的起始處添加一個項目";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "插入在列表中的指定位置的項目。#1 是最後一個項目。";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "插入在列表中的指定位置的項目。#1 是第一個項目。";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "在列表的尾端加入一個項目";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "在列表中隨機插入項目";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "設定列表中的第一個項目";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "設定在列表中的指定位置的項目。#1 是最後一個項目。";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "設定在列表中的指定位置的項目。#1 是第一個項目。";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "設定列表中的最後一個項目";
  Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "設定列表中隨機的一個項目";
  Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
  Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "升冪排序";
  Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "降冪排序";
  Blockly.Msg.LISTS_SORT_TITLE = "依%1%2%3排序";
  Blockly.Msg.LISTS_SORT_TOOLTIP = "排序清單的複製內容";
  Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "依字母排序並忽略大小寫";
  Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "依數字排序";
  Blockly.Msg.LISTS_SORT_TYPE_TEXT = "依字母排序";
  Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists"; // untranslated
  Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "從文本製作列表";
  Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "從列表拆出文本";
  Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "串起文本列表成一個文本，由分隔符分隔。";
  Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "拆分文本到文本列表，按每個分隔符拆分。";
  Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "用分隔符";
  Blockly.Msg.LISTS_STRING_CREATE_WITH_INPUT_WITH = "使用這些值建立字符串列表";
  Blockly.Msg.LISTS_THE_LENGTH_OF = "%1的长度";
  Blockly.Msg.LOGIC_BOOLEAN_FALSE = "否";
  Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values"; // untranslated
  Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "返回 真 或 否。";
  Blockly.Msg.LOGIC_BOOLEAN_TRUE = "真";
  Blockly.Msg.LOGIC_CASE = "情況";
  Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://zh.wikipedia.org/wiki/不等";
  Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "如果這兩個輸入區塊內容相等，返回 真。";
  Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "如果第一個輸入大於第二個輸入，返回 真。";
  Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "如果第一個輸入大於或等於第二個輸入，返回 真。";
  Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "如果第一個輸入小於第二個輸入，返回 真。";
  Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "如果第一個輸入是小於或等於第二個輸入，返回 真。";
  Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "如果這兩個輸入區塊內容不相等，返回 真。";
  Blockly.Msg.LOGIC_DEFAULT = "默認";
  Blockly.Msg.LOGIC_DO = "做";
  Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not"; // untranslated
  Blockly.Msg.LOGIC_NEGATE_TITLE = "非 %1";
  Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "如果輸入的值是 否，則返回 真。如果輸入的值是 真 返回 否。";
  Blockly.Msg.LOGIC_NULL = "空";
  Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type"; // untranslated
  Blockly.Msg.LOGIC_NULL_TOOLTIP = "返回 空。";
  Blockly.Msg.LOGIC_OPERATION_AND = "且";
  Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations"; // untranslated
  Blockly.Msg.LOGIC_OPERATION_OR = "或";
  Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "如果這兩個輸入值都為 真，則返回 真。";
  Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "如果至少一個輸入的值為 真，返回 真。";
  Blockly.Msg.LOGIC_SWITCH = "切換";
  Blockly.Msg.LOGIC_TERNARY_CONDITION = "測試";
  Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://zh.wikipedia.org/wiki/條件運算符";
  Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "如果為非";
  Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "如果為真";
  Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "檢查 'test' 中的條件。如果條件為 真，將返回 '如果為 真' 值 ；否則，返回 '如果為 否' 的值。";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE = "从WiFi模組獲取數據";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE_GET = "從 ";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE_GET_LINE2 = "獲取第";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE_GET_LINE3 = "位的數據，並設定類型為";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE_GET_LINE4 = "";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE_LINE2 = "并存到 ";
  Blockly.Msg.MAINEASYMODE_TRANSFER_RECEIVE_LINE3 = "長度爲 ";
  Blockly.Msg.MAINEASYMODE_TRANSFER_SEND = "創建數組";
  Blockly.Msg.MAINEASYMODE_TRANSFER_SEND_LINE2 = "傳輸數據到WiFi上";
  Blockly.Msg.MAINEASYMODE_TRANSFER_SEND_VALUE = "Data";
  Blockly.Msg.MAINWIFI_RECEIVEMSG = "接收數據到";
  Blockly.Msg.MAINWIFI_RECEIVEMSG_ISSUCCESS = "接收數據成功";
  Blockly.Msg.MAINWIFI_RECEIVEMSG_LENGTH = ",數據長度為";
  Blockly.Msg.MAINWIFI_SENDMSG = "發送數據";
  Blockly.Msg.MAINWIFI_SENDMSG_LENGTH = ",數據長度為";
  Blockly.Msg.MAINWIFI_SETUP = "無線數據傳輸初始化";
  Blockly.Msg.MATH_ADDITION_SYMBOL = "+"; // untranslated
  Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://zh.wikipedia.org/wiki/算術";
  Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "返回兩個數字的總和。";
  Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "返回兩個數字的商。";
  Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "返回兩個數字的差。";
  Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "返回兩個數字的乘積。";
  Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "返回第二個數字的指數的第一個數字。";
  Blockly.Msg.MATH_CHANGE_HELPURL = "https://zh.wikipedia.org/wiki/加法";
  Blockly.Msg.MATH_CHANGE_TITLE = "修改 %1 自 %2";
  Blockly.Msg.MATH_CHANGE_TOOLTIP = "將數字添加到變數 '%1'。";
  Blockly.Msg.MATH_CONSTANT_HELPURL = "https://zh.wikipedia.org/wiki/數學常數";
  Blockly.Msg.MATH_CONSTANT_TOOLTIP = "返回一個的常見常量： π (3.141......)，e (2.718...)、 φ (1.618...)、 開方(2) (1.414......)、 開方(½) (0.707......) 或 ∞ （無窮大）。";
  Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29"; // untranslated
  Blockly.Msg.MATH_CONSTRAIN_TITLE = "限制數字 %1 介於 (低) %2 到 (高) %3";
  Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "限制數字介於兩個指定的數字之間";
  Blockly.Msg.MATH_DIVISION_SYMBOL = "÷"; // untranslated
  Blockly.Msg.MATH_IS_DIVISIBLE_BY = "可被整除";
  Blockly.Msg.MATH_IS_EVEN = "是偶數";
  Blockly.Msg.MATH_IS_NEGATIVE = "是負值";
  Blockly.Msg.MATH_IS_ODD = "是奇數";
  Blockly.Msg.MATH_IS_POSITIVE = "是正值";
  Blockly.Msg.MATH_IS_PRIME = "是質數";
  Blockly.Msg.MATH_IS_TOOLTIP = "如果數字是偶數，奇數，非負整數，正數、 負數或如果它是可被某數字整除，則返回 真 或 否。";
  Blockly.Msg.MATH_IS_WHOLE = "是非負整數";
  Blockly.Msg.MATH_MODULO_HELPURL = "https://zh.wikipedia.org/wiki/模除";
  Blockly.Msg.MATH_MODULO_TITLE = "取餘數自 %1 ÷ %2";
  Blockly.Msg.MATH_MODULO_TOOLTIP = "回傳兩個數字相除的餘數";
  Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×"; // untranslated
  Blockly.Msg.MATH_NUMBER_HELPURL = "https://zh.wikipedia.org/wiki/數";
  Blockly.Msg.MATH_NUMBER_TOOLTIP = "一個數字。";
  Blockly.Msg.MATH_ONLIST_HELPURL = ""; // untranslated
  Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "平均值 自列表";
  Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "最大值 自列表";
  Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "中位數 自列表";
  Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "最小值 自列表";
  Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "比較眾數 自列表";
  Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "隨機抽取 自列表";
  Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "標準差 自列表";
  Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "總和 自列表";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "返回列表中數值的平均值 （算術平均值）。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "返回列表中的最大數字。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "返回列表中數值的中位數。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "返回列表中的最小數字。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "返回一個列表中的最常見項目的列表。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "從列表中返回一個隨機的項目。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "返回列表中數字的標準差。";
  Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "返回列表中的所有數字的總和。";
  Blockly.Msg.MATH_POWER_SYMBOL = "^"; // untranslated
  Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://zh.wikipedia.org/wiki/隨機數生成器";
  Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "取隨機分數";
  Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "返回介於 （包含） 0.0 到 1.0 之間的隨機數。";
  Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://zh.wikipedia.org/wiki/隨機數生成器";
  Blockly.Msg.MATH_RANDOM_INT_TITLE = "取隨機整數介於 (低) %1 到 %2";
  Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "回傳限制的數字區間內的隨機數字";
  Blockly.Msg.MATH_ROUND_HELPURL = "https://zh.wikipedia.org/wiki/數值簡化";
  Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "四捨五入";
  Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "無條件捨去";
  Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "無條件進位";
  Blockly.Msg.MATH_ROUND_TOOLTIP = "將數字向上或向下舍入。";
  Blockly.Msg.MATH_SINGLE_HELPURL = "https://zh.wikipedia.org/wiki/平方根";
  Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "絕對值";
  Blockly.Msg.MATH_SINGLE_OP_ROOT = "開根號";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "返回指定數字的絕對值。";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "返回指定數字指數的 e";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "返回指定數字的自然對數。";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "返回指定數字的對數。";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "返回指定數字的 negation。";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "返回指定數字指數的10的冪次。";
  Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "返回指定數字的平方根。";
  Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-"; // untranslated
  Blockly.Msg.MATH_TRIG_ACOS = "acos"; // untranslated
  Blockly.Msg.MATH_TRIG_ASIN = "asin"; // untranslated
  Blockly.Msg.MATH_TRIG_ATAN = "atan"; // untranslated
  Blockly.Msg.MATH_TRIG_COS = "cos"; // untranslated
  Blockly.Msg.MATH_TRIG_HELPURL = "https://zh.wikipedia.org/wiki/三角函數";
  Blockly.Msg.MATH_TRIG_SIN = "sin"; // untranslated
  Blockly.Msg.MATH_TRIG_TAN = "tan"; // untranslated
  Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "返回指定角度的反餘弦值(非弧度）。";
  Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "返回指定角度的反正弦值(非弧度）。";
  Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "返回指定角度的反正切值。";
  Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "返回指定角度的餘弦值(非弧度）。";
  Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "返回指定角度的正弦值(非弧度）。";
  Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "返回指定角度的正切值(非弧度）。";
  Blockly.Msg.MATH_MAX_MIN_OPERATOR_MAX = "最大值";
  Blockly.Msg.MATH_MAX_MIN_OPERATOR_MIN = "最小值";
  Blockly.Msg.MATH_MAX_MIN_TOOLTIP = "返回两个数字的最大值/最小值";
  Blockly.Msg.MATH_MAX_MIN_HELPURL = "https://www.arduino.cc/reference/en/language/functions/math/max/"
  Blockly.Msg.ME = "我";
  Blockly.Msg.MOTION_GETACC = "獲取";
  Blockly.Msg.MOTION_GETACC1 = "方向的加速度";
  Blockly.Msg.MOTION_GETRAWDATA = "獲得數據";
  Blockly.Msg.MOTION_GETYPR = "獲取";
  Blockly.Msg.MOTION_GETYPR1 = "的旋轉度";
  Blockly.Msg.MOTION_ONDIRECTION = "正在向";
  Blockly.Msg.MOTION_ONDIRECTION1 = "偏转";
  Blockly.Msg.MOTION_ONDIRECTION_BACK = "后";
  Blockly.Msg.MOTION_ONDIRECTION_CLOCKWISE = "順時針";
  Blockly.Msg.MOTION_ONDIRECTION_COUNTERCLOCKWISE = "逆時針";
  Blockly.Msg.MOTION_ONDIRECTION_FRONT = "前";
  Blockly.Msg.MOTION_ONDIRECTION_LEFT = "左";
  Blockly.Msg.MOTION_ONDIRECTION_RIGHT = "右";
  Blockly.Msg.MOTION_ONSHAKE = "正在搖晃";
  Blockly.Msg.MOTION_SETUP = "運動初始化";
  Blockly.Msg.MOTION_TRENDENCY = "獲得運動趨勢";
  Blockly.Msg.MOTOR_MOVE_DIRECTION1 = "順時針";
  Blockly.Msg.MOTOR_MOVE_DIRECTION2 = "逆時針";
  Blockly.Msg.MOTOR_MOVE_MOTOR = "設定馬達";
  Blockly.Msg.MOTOR_MOVE_MSG = "和";
  Blockly.Msg.MOTOR_SETUP = "馬達驅動車設定";
  Blockly.Msg.MOTOR_SPEED = "速度";
  Blockly.Msg.MOTOR_STOP = "設定馬達停止";
  Blockly.Msg.MUSIC_BEAT = "拍";
  Blockly.Msg.MUSIC_DURATION = "持續";
  Blockly.Msg.MUSIC_INSTRUMENT = "設定樂器";
  Blockly.Msg.MUSIC_INSTRUMENT_ACCORION = "手風琴";
  Blockly.Msg.MUSIC_INSTRUMENT_BASS = "貝斯";
  Blockly.Msg.MUSIC_INSTRUMENT_CELLO = "大提琴";
  Blockly.Msg.MUSIC_INSTRUMENT_DRAWBARORGAN = "爵士風琴";
  Blockly.Msg.MUSIC_INSTRUMENT_DRUM = "太鼓";
  Blockly.Msg.MUSIC_INSTRUMENT_EGUITAR = "電吉他";
  Blockly.Msg.MUSIC_INSTRUMENT_EPIANO = "電子琴";
  Blockly.Msg.MUSIC_INSTRUMENT_FLUTE = "長笛";
  Blockly.Msg.MUSIC_INSTRUMENT_GPIANO = "經典鋼琴";
  Blockly.Msg.MUSIC_INSTRUMENT_GUITAR = "吉他";
  Blockly.Msg.MUSIC_INSTRUMENT_MUSICBOX = "八音盒";
  Blockly.Msg.MUSIC_INSTRUMENT_PICCOLO = "短笛";
  Blockly.Msg.MUSIC_INSTRUMENT_SAX = "薩克斯";
  Blockly.Msg.MUSIC_INSTRUMENT_SITAR = "西塔琴";
  Blockly.Msg.MUSIC_INSTRUMENT_TRUMPET = "喇叭";
  Blockly.Msg.MUSIC_INSTRUMENT_VIOLA = "中提琴";
  Blockly.Msg.MUSIC_INSTRUMENT_VIOLIN = "小提琴";
  Blockly.Msg.MUSIC_INSTRUMENT_WHISTLE = "汽笛";
  Blockly.Msg.MUSIC_INSTRUMENT_WOODBLOCK = "木魚";
  Blockly.Msg.MUSIC_INSTRUMENT_XYLOPHONE = "木琴";
  Blockly.Msg.MUSIC_MP3_CURRENTVOLUME = "獲得當前音量";
  Blockly.Msg.MUSIC_MP3_PLAYALL = "播放列表";
  Blockly.Msg.MUSIC_MP3_PLAYALL_NAME = "播放模式";
  Blockly.Msg.MUSIC_MP3_PLAYMODE_LISTREPEAT = "列表循環";
  Blockly.Msg.MUSIC_MP3_PLAYMODE_NORMAL = "單次";
  Blockly.Msg.MUSIC_MP3_PLAYMODE_REPEAT = "單曲循環";
  Blockly.Msg.MUSIC_MP3_PLAYONE = "播放音樂文件";
  Blockly.Msg.MUSIC_MP3_PLAYONE_NAME = "音樂:";
  Blockly.Msg.MUSIC_MP3_PLAYONE_NORMAL = "單次";
  Blockly.Msg.MUSIC_MP3_PLAYONE_REPEAT = "循環";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING = "播放器設置:";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_NEXTSONG = "下一曲";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_PAUSE = "暫停";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_PLAYALL = "播放所有樂曲";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_PRESONG = "上一曲";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_RESUME = "播放";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_STOP = "停止";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_VOLDOWN = "調小音量";
  Blockly.Msg.MUSIC_MP3_PLAYSETTING_VOLUP = "調大音量";
  Blockly.Msg.MUSIC_MP3_PLAY_NORMAL = "順序播放";
  Blockly.Msg.MUSIC_MP3_PLAY_REPEAT = "列表循環";
  Blockly.Msg.MUSIC_MP3_SETUP = "MP3播放器初始化";
  Blockly.Msg.MUSIC_MP3_SETUP_SETVOLUME = "設置音量";
  Blockly.Msg.MUSIC_MP3_SETUP_SETVOLUME_HIGH = "高";
  Blockly.Msg.MUSIC_MP3_SETUP_SETVOLUME_LOW = "低";
  Blockly.Msg.MUSIC_MP3_SETUP_SETVOLUME_MID = "中";
  Blockly.Msg.MUSIC_MP3_SETVOLUME = "設置音量為";
  Blockly.Msg.MUSIC_NOTE = "音階";
  Blockly.Msg.MUSIC_PLAY_NOTE = "播放";
  Blockly.Msg.MUSIC_PLAY_NOTE_TOOLTIP = "right click this block and check the help page to see the corresponding music note."; // untranslated
  Blockly.Msg.MUSIC_REST = "音符間隔";
  Blockly.Msg.MUSIC_VOLUME = "設定音量";
  Blockly.Msg.MUSIC_VOL_MAX = "最大";
  Blockly.Msg.MUSIC_VOL_MIN = "最小";
  Blockly.Msg.Monday = "周一";
  Blockly.Msg.Motion_Accelerate = "加速度";
  Blockly.Msg.Motion_Gyroscope = "陀螺儀";
  Blockly.Msg.NBIOT_ENABLE = "啟用 NB-IoT 序列埠交互指令";
  Blockly.Msg.NBIOT_HTTP_APIKEY = "雲端事件API密匙";
  Blockly.Msg.NBIOT_HTTP_CLOUD_GET = "NB-IoT CocoCloud: Receive Data"; // untranslated
  Blockly.Msg.NBIOT_HTTP_CONTENTTYPE = "Content Type"; // untranslated
  Blockly.Msg.NBIOT_HTTP_DATA = "數據名稱";
  Blockly.Msg.NBIOT_HTTP_IFTTT_APIKEY = "IFTTT API Key";
  Blockly.Msg.NBIOT_HTTP_IFTTT_EVENT = "IFTTT項目名稱";
  Blockly.Msg.NBIOT_HTTP_IFTTT_TITLE = "NB-IoT 連接IFTTT:發送數據";
  Blockly.Msg.NBIOT_HTTP_THINGSPEAK_APIKEY = "事件API密匙";
  Blockly.Msg.NBIOT_HTTP_THINGSPEAK_TITLE = "NB-IoT 連接Thingspeak:發送數據";
  Blockly.Msg.NBIOT_HTTP_TITLE = "NB-IoT 連接CocoCloud:發送數據";
  Blockly.Msg.NBIOT_IS_POWERON = "NB-IoT 模組啓動成功";
  Blockly.Msg.NBIOT_NETWORK_CONNECTED = "網絡連接成功";
  Blockly.Msg.NBIOT_NETWORK_IP = "獲取 NB-IoT 模組 IP 地址";
  Blockly.Msg.NBIOT_SETUP = "NB-IoT 通訊初始化";
  Blockly.Msg.NEW_INSTANCE = "New instance..."; // untranslated
  Blockly.Msg.NEW_INSTANCE_TITLE = "New instance name:"; // untranslated
  Blockly.Msg.NEW_VARIABLE = "新變數...";
  Blockly.Msg.NEW_VARIABLE_TITLE = "新變數名稱:";
  Blockly.Msg.OLED_CENTER_POS = "圓心坐標";
  Blockly.Msg.OLED_CIRCLE = "圓形";
  Blockly.Msg.OLED_CLEAR = "清除";
  Blockly.Msg.OLED_COLOR = "顔色";
  Blockly.Msg.OLED_COORDINATE = "起始點坐標";
  Blockly.Msg.OLED_DRAW = "畫";
  Blockly.Msg.OLED_FALSE = "否";
  Blockly.Msg.OLED_FULL = "實心";
  Blockly.Msg.OLED_HEIGHT = "高";
  Blockly.Msg.OLED_LINE = "綫";
  Blockly.Msg.OLED_LINE_END = "到";
  Blockly.Msg.OLED_LINE_START = "從";
  Blockly.Msg.OLED_POINT = "點";
  Blockly.Msg.OLED_POSITION = "位置";
  Blockly.Msg.OLED_RADIUS = "設置半徑為";
  Blockly.Msg.OLED_RECTANGLE = "矩形";
  Blockly.Msg.OLED_SETROTATION = "將熒幕旋轉至";
  Blockly.Msg.OLED_SETROTATION_DEGREE = "度";
  Blockly.Msg.OLED_SETUP = "OLED屏幕設置";
  Blockly.Msg.OLED_SIZE = "尺寸";
  Blockly.Msg.OLED_STROKED = "空心";
  Blockly.Msg.OLED_TEXT = "文本";
  Blockly.Msg.OLED_TEXTNEWLINE = "換行";
  Blockly.Msg.OLED_TRIANGLE = "三角形";
  Blockly.Msg.OLED_TRUE = "是";
  Blockly.Msg.OLED_WIDTH = "寬";
  Blockly.Msg.ORDINAL_NUMBER_SUFFIX = ""; // untranslated
  Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "允許語句";
  Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "與：";
  Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程式";
  Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "執行使用者定義的函數 '%1'。";
  Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://zh.wikipedia.org/wiki/子程式";
  Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "執行使用者定義的函數 '%1' 並使用它的回傳值";
  Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "與：";
  Blockly.Msg.PROCEDURES_CREATE_DO = "建立 '%1'";
  Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "描述此函數...";
  Blockly.Msg.PROCEDURES_DEFNORETURN_DO = ""; // untranslated
  Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29"; // untranslated
  Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "func1";
  Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "到";
  Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "創建一個無回傳值的函數。";
  Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29"; // untranslated
  Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "回傳";
  Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "創建一個有回傳值的函數。";
  Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "警告: 此函數中有重複的參數。";
  Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "反白顯示函式定義";
  Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause"; // untranslated
  Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "如果值為 真，則返回第二個值。";
  Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "警告: 此積木僅可在定義函式時使用。";
  Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "變數:";
  Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "添加函數輸入。";
  Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "參數";
  Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "添加、刪除或重新排列此函數的輸入。";
  Blockly.Msg.PULSESENSOR_GETBPM = "讀取心率的值為";
  Blockly.Msg.PULSESENSOR_HEARTBEAT_PRINT = "在串口監視器打印心率原始數據";
  Blockly.Msg.PULSESENSOR_HEARTBEAT_WHEN = "當心率跳動時";
  Blockly.Msg.PULSESENSOR_HEARTBEAT_WHENNO = "當心率未跳動時";
  Blockly.Msg.PULSESENSOR_SETUP = "心率傳感設置";
  Blockly.Msg.PULSESENSOR_SETUP_1 = "設置傳感器的接口為";
  Blockly.Msg.READ_B = "讀取藍";
  Blockly.Msg.READ_G = "讀取綠";
  Blockly.Msg.READ_R = "讀取紅";
  Blockly.Msg.RED = "紅";
  Blockly.Msg.REDO = "重試";
  Blockly.Msg.REMOVE_COMMENT = "移除註解";
  Blockly.Msg.RENAME_INSTANCE = "Rename instance..."; // untranslated
  Blockly.Msg.RENAME_INSTANCE_TITLE = "Rename all '%1' instances to:"; // untranslated
  Blockly.Msg.RENAME_VARIABLE = "重新命名變數...";
  Blockly.Msg.RENAME_VARIABLE_TITLE = "將所有 \"%1\" 變數重新命名為:";
  Blockly.Msg.REQUEST_DATA_CLOUD = "雲端數據";
  Blockly.Msg.REQUEST_DATA_STRING = "字符串";
  Blockly.Msg.RFID_READID = "讀取卡片ID";
  Blockly.Msg.RFID_SETUP = "RFID初始化";
  Blockly.Msg.ROBOT_SETMOVE_MOVEMENT = "設置雙足的動作";
  Blockly.Msg.ROBOT_SETMOVE_TEMPO = "在速度為";
  Blockly.Msg.ROBOT_SETUP = "雙足行走機器人設置";
  Blockly.Msg.ROBOT_SETUP_SETRLPIN = "和左腳接口";
  Blockly.Msg.ROBOT_SETUP_SETRRPIN = "設置右腳接口";
  Blockly.Msg.ROBOT_SETUP_SETYLPIN = "和左膝接口";
  Blockly.Msg.ROBOT_SETUP_SETYRPIN = "設置右膝接口";
  Blockly.Msg.RTC_DAY = "日";
  Blockly.Msg.RTC_GETDATE = "獲取當前日期";
  Blockly.Msg.RTC_GETTIME = "獲取當前時間";
  Blockly.Msg.RTC_GETWEEK = "獲取當前周数";
  Blockly.Msg.RTC_HOUR = "時";
  Blockly.Msg.RTC_MINUTE = "分";
  Blockly.Msg.RTC_MONTH = "月";
  Blockly.Msg.RTC_SECOND = "秒";
  Blockly.Msg.RTC_SETDATE = "日期";
  Blockly.Msg.RTC_SETDATETIME = "設置日期時間";
  Blockly.Msg.RTC_SETTIME = "時鐘";
  Blockly.Msg.RTC_SETUP = "RTC初始化";
  Blockly.Msg.RTC_SETWEEK = "周数";
  Blockly.Msg.RTC_WEEK = "周";
  Blockly.Msg.RTC_YEAR = "年";
  Blockly.Msg.SONAR = "超聲波";
  Blockly.Msg.SONAR_READ_DIST = "讀取距離從";
  Blockly.Msg.SONAR_SETUP = "設置";
  Blockly.Msg.SONAR_SETUP_ECHOPIN = "和 Echo";
  Blockly.Msg.SONAR_SETUP_MAXDIST = "設置最大距離";
  Blockly.Msg.SONAR_SETUP_TRIGPIN = "設置 Trig";
  Blockly.Msg.Saturday = "周六";
  Blockly.Msg.Sunday = "周日";
  Blockly.Msg.TEXT_APPEND_APPENDTEXT = "後加入文字";
  Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification"; // untranslated
  Blockly.Msg.TEXT_APPEND_TO = "在";
  Blockly.Msg.TEXT_APPEND_TOOLTIP = "將一些文字追加到變數 '%1'。";
  Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case"; // untranslated
  Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "轉成 小寫";
  Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "轉成 首字母大寫";
  Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "轉成 大寫";
  Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "使用不同的大小寫複製這段文字。";
  Blockly.Msg.TEXT_CHARAT_FIRST = "取第一個字元";
  Blockly.Msg.TEXT_CHARAT_FROM_END = "取得 倒數第 # 個字元";
  Blockly.Msg.TEXT_CHARAT_FROM_START = "取得 字元 #";
  Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text"; // untranslated
  Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "的字元在字串";
  Blockly.Msg.TEXT_CHARAT_LAST = "取最後一個字元";
  Blockly.Msg.TEXT_CHARAT_RANDOM = "取隨機一個字元";
  Blockly.Msg.TEXT_CHARAT_TAIL = "";
  Blockly.Msg.TEXT_CHARAT_TOOLTIP = "返回位於指定位置的字元。";
  Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "將一個項目加入到字串中。";
  Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "加入";
  Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "添加、 刪除或重新排列各區塊來此重新配置這個文字積木。";
  Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "到 倒數第 # 個字元";
  Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "到 字元 #";
  Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "到 最後一個字元";
  Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text"; // untranslated
  Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "自字串";
  Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "取得一段字串 自 第一個字元";
  Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "取得一段字串自 #";
  Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "取得一段字串自 #";
  Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = ""; // untranslated
  Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "返回指定的部分文字。";
  Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text"; // untranslated
  Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "在字串";
  Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "尋找 第一個 出現的字串";
  Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "尋找 最後一個 出現的字串";
  Blockly.Msg.TEXT_INDEXOF_TAIL = ""; // untranslated
  Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "返回在第二個字串中的第一個/最後一個匹配項目的索引值。如果未找到則返回 0。";
  Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text"; // untranslated
  Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 為空";
  Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "如果提供的字串為空，則返回 真。";
  Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation"; // untranslated
  Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "建立字串使用";
  Blockly.Msg.TEXT_JOIN_TOOLTIP = "通過串起任意數量的項目來建立一段文字。";
  Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification"; // untranslated
  Blockly.Msg.TEXT_LENGTH_TITLE = "長度 %1";
  Blockly.Msg.TEXT_LENGTH_TOOLTIP = "返回這串文字的字元數（含空格） 。";
  Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text"; // untranslated
  Blockly.Msg.TEXT_PRINT_TITLE = "印出 %1";
  Blockly.Msg.TEXT_PRINT_TOOLTIP = "印出指定的文字、 數字或其他值。";
  Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user"; // untranslated
  Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "輸入數字";
  Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "輸入文字";
  Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "輸入 數字 並顯示提示訊息";
  Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "輸入 文字 並顯示提示訊息";
  Blockly.Msg.TEXT_TEXT_HELPURL = "https://zh.wikipedia.org/wiki/字串";
  Blockly.Msg.TEXT_TEXT_TOOLTIP = "字元、 單詞或一行文字。";
  Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces"; // untranslated
  Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "消除兩側空格";
  Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "消除左側空格";
  Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "消除右側空格";
  Blockly.Msg.TEXT_TRIM_TOOLTIP = "複製這段文字的同時刪除兩端多餘的空格。";
  Blockly.Msg.THINGSPEAK_CREATE_WITH_CONTAINER_TITLE_ADD = "Field";
  Blockly.Msg.THINGSPEAK_CREATE_WITH_INPUT_WITH = "FIELD";
  Blockly.Msg.THINGSPEAK_CREATE_WITH_ITEM_TITLE = "value";
  Blockly.Msg.TODAY = "今天";
  Blockly.Msg.TOUCH_AT = "觸摸傳感接口 ";
  Blockly.Msg.TOUCH_CASE = "按鍵";
  Blockly.Msg.TOUCH_DEFAULT = "默認";
  Blockly.Msg.TOUCH_DO = "執行";
  Blockly.Msg.TOUCH_LOOSE = "儅鬆開時";
  Blockly.Msg.TOUCH_SETUP = "觸摸感應設置";
  Blockly.Msg.TOUCH_SWITCH = "⌘ 當觸碰傳感接口";
  Blockly.Msg.TOUCH_THEN_LOOSE_SWITCH = "⌘ 儅鬆開被觸碰的接口";
  Blockly.Msg.Thursday = "周四";
  Blockly.Msg.Tuesday = "周二";
  Blockly.Msg.UNDO = "還原";
  Blockly.Msg.VARIABLES_DEFAULT_NAME = "item"; // untranslated
  Blockly.Msg.VARIABLES_GET_CREATE_SET = "建立 '設定 %1'";
  Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get"; // untranslated
  Blockly.Msg.VARIABLES_GET_TOOLTIP = "返回此變數的值。";
  Blockly.Msg.VARIABLES_SET = "賦值 %1 為 %2";
  Blockly.Msg.VARIABLES_SET_CREATE_GET = "建立 '取得 %1'";
  Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set"; // untranslated
  Blockly.Msg.VARIABLES_SET_TOOLTIP = "設定此變數，好和輸入值相等。";
  Blockly.Msg.WATERTEMP_GET_TEMP = "獲取水溫數據 (ºC)";
  Blockly.Msg.WATERTEMP_SETUP_ATTACHED_PIN = "數位引腳設定:";
  Blockly.Msg.WATERTEMP_SETUP_BLOCKNAME = "水溫感應器";
  Blockly.Msg.WATERTEMP_SETUP_SENSORTYPE = "感應器型號:";
  Blockly.Msg.WATERTEMP_SETUP_SETUP = "初始化";
  Blockly.Msg.WEBPAGE_BUTTONCTRL_SETPATH = " set path to:"; // untranslated
  Blockly.Msg.WEBPAGE_BUTTONCTRL_TEXT_BOTTOM = "設定底部按鈕為:";
  Blockly.Msg.WEBPAGE_BUTTONCTRL_TEXT_CENTER = "設定中間按鈕為:";
  Blockly.Msg.WEBPAGE_BUTTONCTRL_TEXT_LEFT = "設定左側按鈕為:";
  Blockly.Msg.WEBPAGE_BUTTONCTRL_TEXT_RIGHT = "設定右側按鈕為:";
  Blockly.Msg.WEBPAGE_BUTTONCTRL_TEXT_TOP = "設定頂部按鈕為:";
  Blockly.Msg.WEBPAGE_BUTTONCTRL_TITLE = "網頁控制面板: 按鍵控制器";
  Blockly.Msg.WEBPAGE_BUTTON_NAME = "按鈕名稱";
  Blockly.Msg.WEBPAGE_BUTTON_ROUTER = "設定請求路徑為:";
  Blockly.Msg.WEBPAGE_BUTTON_TITLE = "網頁控制面板: 按鈕";
  Blockly.Msg.WEBPAGE_COLORPICKER_PATH = "設定請求路徑為:";
  Blockly.Msg.WEBPAGE_COLORPICKER_SUBTITLE = "*注意: 傳輸的顏色資料為 RGB 顏色制式";
  Blockly.Msg.WEBPAGE_COLORPICKER_TITLE = "網頁控制面板: 取色器控制元件";
  Blockly.Msg.WEBPAGE_LABLE = "標籤名稱";
  Blockly.Msg.WEBPAGE_LABLE_TITLE = "網頁控制面板: 文字";
  Blockly.Msg.WIFICLIENT_HTTP_GET_DATA = "獲取數據并存到";
  Blockly.Msg.WIFICLIENT_HTTP_GET_URL = "發送GET請求到";
  Blockly.Msg.WIFICLIENT_HTTP_POST_DATA = "數據";
  Blockly.Msg.WIFICLIENT_HTTP_POST_TYPE = "類型爲";
  Blockly.Msg.WIFICLIENT_HTTP_POST_URL = "發送POST請求到";
  Blockly.Msg.WIFICLIENT_HTTP_POST_VAR = "創建數組";
  Blockly.Msg.WIFICLIENT_HTTP_PUT_DATA = "要發送内容";
  Blockly.Msg.WIFICLIENT_HTTP_PUT_TYPE = "類型爲";
  Blockly.Msg.WIFICLIENT_HTTP_PUT_URL = "發送PUT請求到";
  Blockly.Msg.WIFICLIENT_HTTP_RESPONSE = "獲得HTTP響應";
  Blockly.Msg.WIFICLIENT_HTTP_SETUP = "客戶端初始化";
  Blockly.Msg.WIFICLIENT_RECEIVE_GET = "從";
  Blockly.Msg.WIFICLIENT_RECEIVE_GET_LINE2 = "獲取第";
  Blockly.Msg.WIFICLIENT_RECEIVE_GET_LINE3 = "位的數據,類型爲";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_END = "值";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_GETDATA = "獲取數據並將其存到";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_KEY = "從";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_KEY1 = "獲取雲端項目中";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_KEY2 = "屬性名爲";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_SENDDATA = "發送數據:";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_SETVAR = "變數";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_SETVAR_FROM = "";
  Blockly.Msg.WIFIEASYMODE_COCOCLOUD_TYPE = "的";
  Blockly.Msg.WIFIEASYMODE_COCOClOUD_DATA_NAME = "數據名:";
  Blockly.Msg.WIFIEASYMODE_COCOClOUD_EVENT = "Cloud Event API Key :";
  Blockly.Msg.WIFIEASYMODE_IFTTT_EVENT = "IFTTT項目名稱:";
  Blockly.Msg.WIFIEASYMODE_IFTTT_FETCH = "獲取數據";
  Blockly.Msg.WIFIEASYMODE_IFTTT_KEY = "IFTTT Key:";
  Blockly.Msg.WIFIEASYMODE_IFTTT_POST = "發送數據";
  Blockly.Msg.WIFIEASYMODE_IFTTT_SENDDATA = "發送數據:";
  Blockly.Msg.WIFIEASYMODE_IFTTT_TYPE = "Webhook類型:";
  Blockly.Msg.WIFIEASYMODE_NETWORK_PW = "密碼:";
  Blockly.Msg.WIFIEASYMODE_NETWORK_SSID = "SSID:";
  Blockly.Msg.WIFIEASYMODE_NETWORK_TITLE = "連接Wi-Fi";
  Blockly.Msg.WIFIEASYMODE_THINGSPEAK_APIKEY = "Channel API Key:";
  Blockly.Msg.WIFIEASYMODE_THINGSPEAK_SENDDATA = "發送數據:";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE = "從主機板獲取數據";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE_GET = "從";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE_GET_LINE2 = "獲取第";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE_GET_LINE3 = "位的數據，並設定類型為";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE_GET_LINE4 = "";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE_LINE2 = "并存到";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_RECEIVE_LINE3 = "長度爲 ";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_SEND = "創建數組";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_SEND_LINE2 = "傳輸數據到主機板上";
  Blockly.Msg.WIFIEASYMODE_TRANSFER_SEND_VALUE = "Data";
  Blockly.Msg.WIFINETWORK_AP_PW = "密碼:";
  Blockly.Msg.WIFINETWORK_AP_SETUP = "建立Wi-Fi熱點";
  Blockly.Msg.WIFINETWORK_AP_SSID = "SSID:";
  Blockly.Msg.WIFINETWORK_CONNECT = "連接Wi-Fi";
  Blockly.Msg.WIFINETWORK_CONNECT_PW = "密碼:";
  Blockly.Msg.WIFINETWORK_CONNECT_SSID = "SSID:";
  Blockly.Msg.WIFINETWORK_GETGATEWAYIP = "獲取網關IP";
  Blockly.Msg.WIFINETWORK_GETLOCALIP = "獲取本地IP";
  Blockly.Msg.WIFINETWORK_GETMACADDR = "獲取MAC地址";
  Blockly.Msg.WIFINETWORK_GETSTATIONNUM = "獲取連接設備數量";
  Blockly.Msg.WIFINETWORK_ISCONNECTED = "是否連接成功";
  Blockly.Msg.WIFINETWORK_PW_WARN = "密碼設置應該超過8位";
  Blockly.Msg.WIFISERVER_HANDLECLIENT = "handleclient";
  Blockly.Msg.WIFISERVER_LIST = "創建數組";
  Blockly.Msg.WIFISERVER_RECEIVE = "服務器接收數據";
  Blockly.Msg.WIFISERVER_RECEIVE_GET = "從";
  Blockly.Msg.WIFISERVER_RECEIVE_GET_INT = "數字";
  Blockly.Msg.WIFISERVER_RECEIVE_GET_LINE2 = "獲取第";
  Blockly.Msg.WIFISERVER_RECEIVE_GET_LINE3 = "位的值,類型爲";
  Blockly.Msg.WIFISERVER_RECEIVE_GET_STRING = "字符串";
  Blockly.Msg.WIFISERVER_RECEIVE_LENGTH = "長度爲";
  Blockly.Msg.WIFISERVER_RECEIVE_TO = "並存儲到";
  Blockly.Msg.WIFISERVER_SEND = "服務器發送數據";
  Blockly.Msg.WIFISERVER_SERVERSEND = "服務器 推送 ";
  Blockly.Msg.WIFISERVER_SERVERSEND_CODE = "HTTP 状态碼";
  Blockly.Msg.WIFISERVER_SERVERSEND_CONTENT = "内容";
  Blockly.Msg.WIFISERVER_SERVERSEND_TYPE = "類型";
  Blockly.Msg.WIFISERVER_SETROOTPAGE = "設置主頁";
  Blockly.Msg.WIFISERVER_SETROUTER = "服務器路由";
  Blockly.Msg.WIFISERVER_SETROUTER_ONNOTFOUND = "設置服務器路由当不存在URL时, 處理";
  Blockly.Msg.WIFISERVER_SETROUTER_SET = "設置路由";
  Blockly.Msg.WIFISERVER_SETROUTER_WITH = "響應";
  Blockly.Msg.WIFISERVER_SETUP = "服務器初始化";
  Blockly.Msg.WIFISERVER_WAIT_CONNECTION = "等待連接";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT = "Web服務 IFTTT";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_EVENT = "Event";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_KEY = "Api-Key ";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_KEY1 = "Key1";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_KEY2 = "Key2";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_KEY3 = "Key3";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_VALUE1 = "Value1";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_VALUE2 = "Value2";
  Blockly.Msg.WIFIWEBSERVICES_IFTTT_SET_VALUE3 = "Value3";
  Blockly.Msg.WIFIWEBSERVICES_THINKSPEAK = "Web服務 Thinkspeak";
  Blockly.Msg.WIFIWEBSERVICES_THINKSPEAK_SET_FIELD1 = "Field";
  Blockly.Msg.WIFIWEBSERVICES_THINKSPEAK_SET_KEY = "Api-key";
  Blockly.Msg.WIFIWEBSERVICES_THINKSPEAK_SET_VALUE = "Value";
  Blockly.Msg.WIFI_RECEIVEMSG = "接收數據至";
  Blockly.Msg.WIFI_RECEIVEMSG_ISSUCCESS = "接收數據成功";
  Blockly.Msg.WIFI_RECEIVEMSG_LENGTH = ", 數據長度 ";
  Blockly.Msg.WIFI_SENDMSG = "發送數據 ";
  Blockly.Msg.WIFI_SENDMSG_LENGTH = ", 數據長度 ";
  Blockly.Msg.WIFI_SETUP = "輸出傳輸初始化";
  Blockly.Msg.Wednesday = "周三";
  Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
  Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
  Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
  Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
  Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
  Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
  Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
  Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
  Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
  Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
  Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
  Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
  Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
  Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
  Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
  Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
  Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
  Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
  Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
  Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;
}

export default LoadArduinoMsgHant;
